### PR TITLE
Add the 1to1 mode (-1:1 range) to the image classifier application

### PR DESCRIPTION
**Pull request by tlepley**
We are working with models trained for inputs in the -1:1 range.
This small PR then proposes to add the "1to1" mode to the image classifier application.

### CODE REVIEW

**Comment by jfix71** [comment]
@tlepley Thanks for working on this!

I think I would prefer this mode to be called something like `neg1to1` instead of `1to1`. Any objections?

**Comment by tlepley** [comment]
@jfix71 I agree  `neg1to1`  is more explicit, but I picked this `1to1` name simply to be consistent with the existing `128to127` mode (values are in the range: -128 .. 127). If I rename `1to1` into `neg1to1`, I think we should also rename `128to127` into `neg128to127`. Any opinion ?

**Comment by jfix71** [comment]
@tlepley Yeah I agree, let's change both then. Thanks!

**Comment by bertmaher** [comment]
If you change 128to127 can you also update tests/images/run.sh?  Thanks!

**Comment by tlepley** [comment]
@jfix71 @bertmaher Done.

**Pull request merged**
