### PR TITLE
Update thresholds for ParameterSweepTest.

### PR DESCRIPTION
**Pull request by jsubag**
Summary: Updating thresholds for FC, BatchMatMul and Conv sweep tests.

### CODE REVIEW

**Comment by jsubag** [comment]
@jfix71 , @arunm-git Please take a look.

**Comment by jsubag** [comment]
CC: @omromano

**Comment by jfix71** [comment]
@hyuen Can you take a look here?

**Comment by hyuen** [comment]
@jfix71  and I met and discussed about this. It seems right now that we are comparing fp32 as a baseline vs a quantized approach. The error threshold is dependent on the dimensions of the inputs, and by changing these thresholds (extending them) we are just accepting the biggest error which comes from the biggest dimension.

The proposed fix is to compare with a baseline in the same precision, and expect bitwise accuracy for most of the cases, that way we can flush out any differences in the quantization or accumulator schemes.

**Comment by jsubag** [comment]
@hyuen I'm all for comparing with a more accurate reference - but skeptical about _bitwise_ comparisons for non-integer arithmetic (especially across different HW).
Can you share more details about your reference model?

**Pull request closed without merging**
