### PR TITLE
64b bias for XIConv bias

### PR DESCRIPTION
**Pull request by lzao-cadence**
Summary:

Add supports for 64b bias for XIConv node.

### CODE REVIEW

**Review by zrphercule — APPROVED** [review]
LGTM, thanks!

**Comment by zrphercule** [comment]
Could you please sign the CLA? Thanks!

**Comment by lzao-cadence** [comment]
Hi Rui,
  Thanks a lot for the review.
  My management told me that there is no need to sign the CLA. They just need to add me to some list, which I guess is equivalent to signing CLA.

Hi Frank,
  When would I be added to the list?

Thanks,
Zao

**Comment by lzao-cadence** [comment]
Hi Rui,
  I have just got through CLA.
  Also, all the tests of this pull request has passed.
Thanks,
Zao

**Review by mortzur — COMMENTED** [review]
Can you please add a case for the new type here https://github.com/pytorch/glow/blob/master/torch_glow/src/PyTorchCommon.cpp#L211 ?

**Comment by lzao-cadence** [comment]
Hi mortzur,
  I have added the case for the new type.
Zao

**Comment by lzao-cadence** [comment]
Ping

**Comment by lzao-cadence** [comment]
Ping, all checks have passed.

**Comment by lzao-cadence** [comment]
Ping

**Comment by lzao-cadence** [comment]
Ping @mortzur @zrphercule

**Pull request closed without merging**
