### PR TITLE
Fixes libjit under MSVC compiling.

### PR DESCRIPTION
**Pull request by lygstate**

### CODE REVIEW

**Comment by nadavrot** [comment]
@lygstate I have a few problem with this commit. First, please don't add LIBJIT_VLA. We don't need it. You can change the few uses of variable-length array to fixed-size arrays. Please take a look at the code. 

Second, this commit bundles a bunch of changes that make it difficult for me to review this code. Please split this commit to small changes that people can review.

**Comment by lygstate** [comment]
@nadavrot What's tie fixd-size length? clarify it clearly.

**Comment by lygstate** [comment]
@nadavrot Are you people refuse to add MSVC support, if that the plan, then I would cancel the work. This pull request is small enough and can not be split.

**Comment by lygstate** [comment]
@nadavrot   What's the maximal size of ywidth?

**Comment by lygstate** [comment]
@nadavrot You've tolkd me these small changes a too big to review, for me, the code is even harder to read. tell clearly where the maximal possible size that doesn't need the VLA support.

**Comment by nadavrot** [comment]
@lygstate For the max number of dimensions you can use the value 10. For the max number of registers you can use the value 32. Please add a comment that explains the max number of supported reg/dims.

**Comment by lygstate** [comment]
how about ywidth and depthUnroll

**Comment by nadavrot** [comment]
@lygstate 32 should be large enough.

**Pull request closed without merging**
