### PR TITLE
[Logging] Added msgs from HostManager and Provisioner under debug build

### PR DESCRIPTION
**Pull request by hupreti**
Summary: Added messages from HostManager.cpp and Provisioner.cpp under debug build.

Documentation: None

Test Plan: None

### CODE REVIEW

**Comment by hupreti** [comment]
Hi @jfix71 can you kindly review these changes?

**Review by jfix71 — CHANGES_REQUESTED** [review]
Hi @hupreti -- I think we'd prefer to keep these internally, can you wrap these in `#if FACEBOOK_INTERNAL` instead?

**Comment by hupreti** [comment]
> Hi @hupreti -- I think we'd prefer to keep these internally, can you wrap these in `#if FACEBOOK_INTERNAL` instead?

Hi @jfix71, requested changes are done. Sorry for the delay.

**Review by jfix71 — APPROVED** [review]
Thanks!

**Pull request closed without merging**
