### PR TITLE
[GraphOptimizer] Optimize Convolution nodes with small input

### PR DESCRIPTION
**Pull request by aturetsk**
Summary:
Optimize Convolution nodes with small input tensors by reducing filters and removing unnecessary padding.
Some networks are designed to support multiple input image resolutions. Freezing such networks to a specific resolution can cause some Convolution nodes at the end of the graph to work on a very small input (less than kernel size) and non-zero padding. By removing pads and reducing filters of such nodes, we can improve filters quantization precision, as well as have tiny performance improvement.

Documentation:
N/A

Test Plan:
Added GraphOptz unit test.

### CODE REVIEW

**Comment by mciprian13** [comment]
@aturetsk The coincidence is that I also need this type of optimization. Do you think you could generalize it for any filter data type (not just float) maybe by using a Slice node (which should get optimized anyway if the filter is constant). WDYT?

**Comment by aturetsk** [comment]
@mciprian13, done.

**Comment by aturetsk** [comment]
Ping

**Review by jfix71 — APPROVED** [review]
Cool, LGTM!

**Pull request closed without merging**
