### PR TITLE
[quantization/optimization] Slice might reduce the dynamic range, but no need to rescale in this case.

### PR DESCRIPTION
**Pull request by rdzhabarov**
No more rescaling after Slice node
optimization

This optimization removes around 120 RescaleQuantizedNodes from sequence to sequence NN.

Note: Slice behavior is covered by Quantization End2End test.

### CODE REVIEW

**Comment by nadavrot** [comment]
@rdzhabarov Would it be possible to implement this optimization in the optimizer?

**Comment by rdzhabarov** [comment]
@nadavrot it's going to be tedious as there will be a Slice -> Rescale -> SomeotherNode and if we just remove Rescale, we'd need to make sure that SomeotherNode has the proper input type, which would mean we need to recreate that node. As it might be any node that's going to be a huge switch on that node kind. I'm open to suggestions if it's possible to avoid this dance.

**Comment by nadavrot** [comment]
@rdzhabarov Is the problem that we can't perform replace-all-uses-with because it will change the type?

**Comment by rdzhabarov** [comment]
@nadavrot yes, so here is what happens.
Slice (out type1) -> Rescale (out type2) -> (in type 2)SomeOtherNode.
Slice output is not compatible with the input of SomeotherNode and replaceAllUsesWith fails on this.
We discussed this with @opti-mix about general purpose pattern matching and replacement but this seemed to be overkill for what use cases we have at the moment.

**Comment by nadavrot** [comment]
@rdzhabarov I think that we can totally simplify this if we allow replaceAllUsesOfWith to substitute the value with a different type. One way to allow this would be to add a flag to RAUW that specifies if the new value must be verified to be of the same type.

**Comment by rdzhabarov** [comment]
@nadavrot that should work, but I worry that by doing this we could accidentally break types when we do not intend to.
One way is to introduce additional boolean param to replaceAllUsagesWith (force type or something like that) and make that "false" by default. In this case, when we absolutely sure that we need to enforce type change we will.

**Comment by rdzhabarov** [comment]
I'm going to take a route of introducing additional default param to the replaceAllUsagesWith method in order to force type change. Closing this PR for now, thanks for comments.

**Comment by rdzhabarov** [comment]
It seems like, considering tradeoffs outlined in the https://github.com/pytorch/glow/pull/988, this is the best way to approach the problem at this point.

**Pull request closed without merging**
