### PR TITLE
Support for S16/S8/U16 numpy values. Default mean/stddev/normalization is now "PassThrough".

### PR DESCRIPTION
**Pull request by vuzelac-cadence**
Allow for loading S16, S8 and U8 numpy files. 

Default normalization, mean, stddev is now "passthrough" - that means that pixel values from an image are unaltered.

A new cmd line option, "input-values-range" allows for setting the range for the input image pixel values. For example, this allows for loading float values as e.g. U8.

### CODE REVIEW

**Comment by vuzelac-cadence** [comment]
unrelated failure.

**Comment by vuzelac-cadence** [comment]
pinging

**Comment by vuzelac-cadence** [comment]
@jfix71

**Comment by vuzelac-cadence** [comment]
@jfix71 @zrphercule @khabinov, #5571 is reviewed and accepted before this one. Is it ok to review out of order ? Not a big deal to rebase but just thinking if this is a normal practice ?

**Review by jfix71 — APPROVED** [review]
LGTM

We take a pretty unorganized approach to reviewing 😛  if you have a desire for ordering specific PRs then just be explicit about it in the comments/description.

**Pull request closed without merging**
