### PR TITLE
[Interpreter Backend] Add support for CollectRpnProposals operator

### PR DESCRIPTION
**Pull request by hupreti**
Summary:
Adding support for CollectRpnProposals operator. This PR contains interpreter backend implementation along with Interpreter Operator Test for the operator.

Documentation: None

Test Plan: Manual Testing and test cases added in InterpreterOperatorTest

### CODE REVIEW

**Comment by hupreti** [comment]
Hi @jfix71,
Kindly help to review the PR.

**Comment by hupreti** [comment]
Hi @jfix71,
Can you please review this?

**Comment by hupreti** [comment]
Hi @jfix71, Kindly review these changes.

**Review by mortzur — APPROVED** [review]
LGTM. I'm sorry for the horrible delay.

**Pull request closed without merging**
