### PR TITLE
[unittests] Organize our tests/unittests/CMakeLists.txt better

### PR DESCRIPTION
**Pull request by bertmaher**
*Description*: The haphazard organization of our unittests CMakeLists did not spark joy.
*Testing*: ninja all && ninja test
*Documentation*: n/a

### CODE REVIEW

**Comment by rdzhabarov** [comment]
> Make test names match cpp files

+1

**Comment by rdzhabarov** [comment]
Have you changed any of the test dependencies as well? (the diff is kinda hard to compare :P)

**Comment by bertmaher** [comment]
Heh, sorry, the individual commits that make up this PR should be a bit easier to look through.  The "alphabetize" one shuffles stuff around and then the others just do bits of isolated cleanup.

To answer your question, though, there are no functional changes in this diff, other than that I made HyphenTest a standalone binary (for no terribly pressing reason other than making it less of a special snowflake that was conditionally added to BackendCorrectnessTest).

**Comment by bertmaher** [comment]
Gonna hurry up and land this before it sprouts merge conflicts.  If there are any complaints I'm more than happy to address them in a follow-up!

**Pull request merged**
