### PR TITLE
Second try to building glow under Windows.

### PR DESCRIPTION
**Pull request by lygstate**

### CODE REVIEW

**Comment by nadavrot** [comment]
@lygstate This PR has some really good stuff, but I don't want to approve it as-is because it has 7 commits that touch a bunch of places. Also, some of the changes don't make sense to me. For example, the LIBJIT_VLA stuff. 

Can you start by upstreaming the simple changes? For example, adding headers, adding the F suffix, etc?

Please use one or two commits per PR to make the code reviewable.

**Comment by lygstate** [comment]
@nadavrot LIBJIT_VLA is necessary, because bitcode could not use dynamic memory allocation.
And for visual studio, it doesn't support for VLA

**Comment by nadavrot** [comment]
Thank you for breaking this PR to multiple small PRs.

**Comment by lygstate** [comment]
@nadavrot  Doe not close this pull, I need it to trigger the ci

**Comment by ayermolo** [comment]
Hello
I see this pull request closed, but I don't see the code in master. Was it not integrated?

**Comment by lygstate** [comment]
Updated with new one.

**Comment by ayermolo** [comment]
Ah I see. Are you planning on adding one for "Fixes compiling errors for Visual Studio."?

**Pull request closed without merging**
