### PR TITLE
Rename VGG16 model to ZFNet512

### PR DESCRIPTION
**Pull request by hegemanjwh2**
This commit renames our "vgg16" model -- which was *not* VGG16, to "ZFNet512" everywhere.  This represents the fact that the model in question is actually almost the ZFNet model of https://arxiv.org/pdf/1311.2901.pdf, with the exception that the 4th convolution has depth only 512 instead of the listed depth of 1024 (see Zeiler & Fergus Table 3).

This commit will not be fully functional until the data in Amazon S3 is moved.

### CODE REVIEW

**Comment by hegemanjwh2** [comment]
We also need to fiddle a little bit with the model's predict_net.pb/predict_net.pbtxt before this commit should be landed, too...

**Comment by rdzhabarov** [comment]
LGTM, one question, @hegemanjwh2 do we have "ZFNet512" name aligned with what Caffe2 or Onnx have at the moment?

**Comment by hegemanjwh2** [comment]
@rdzhabarov - Yes, we think we do...  ;-)

**Comment by hegemanjwh2** [comment]
Will test this out with @bertmaher 's updates to S3 and then land.

**Comment by hegemanjwh2** [comment]
Tests looks good.  Going to land.

**Pull request merged**
