### PR TITLE
[Quantization] Fix optimizeKL with SymmetricWithUsigned schema

### PR DESCRIPTION
**Pull request by hupreti**
Summary: This PR fixes issue of optimizeKL function falling into assert while using SymmetricWithUsigned schema. By construction in Quantization/Base/Base.cpp we always have min >=0 for SymmetricWithUnsigned schema and symmetric flag is also set to true. This is contradictory to the assert statements histMin < 0 in optmizeKL function.

Documentation: None

Test Plan: Unit testing. Modified the existing quantizeTensorTest(s).

### CODE REVIEW

**Comment by hupreti** [comment]
@jfix71 Kindly help to review the changes

**Review by jfix71 — CHANGES_REQUESTED** [review]
Hi @hupreti -- thanks for the fix. Question though -- it looks like you've changed all tests using `quantizeTensorTest` to now use KLMinimization. I wonder if we should create copies of these tests so we can get coverage for both? It's a bit annoying to copy/paste since it's mostly just boilerplate, maybe we could add in gtest parameter sweeping to make this a little cleaner/less boilerplate, though it would be a bit harder.

Also looks like you need to sign the CLA.

**Comment by hupreti** [comment]
Hi @jfix71, I have separated the tests using KLMinimization from those not using KLMinimization. Please review.

**Review by jfix71 — APPROVED** [review]
LGTM as is, thanks!

**Pull request closed without merging**
