### PR TITLE
Add support for printing better log information on OnnxModelLoader

### PR DESCRIPTION
**Pull request by vbaddi**
Summary: 

1.  Add support for printing better log information on OnnxModelLoader
2.  Will capture logs on operator failure errors using operator names and instances

Documentation: None

Test Plan: Ninja Test is run.

### CODE REVIEW

**Comment by vbaddi** [comment]
@jfix71 could you please review this change?

**Comment by mciprian13** [comment]
@vbaddi I think it would be cleaner here to have an utility function similar to the one used in `TFLiteModelLoader.cpp` namely the `opErrMsg` function which would concatenate the operator type and instance name to an error string such that it would be easier to use like this:
```
RETURN_ERR_IF_NOT(startsC, opErrMsg(op, "Starts Tensor is not Constant."));
```
WDYT?

**Comment by vbaddi** [comment]
@mciprian13 , Thanks for pointing out.
Sure., i will follow the similar format for logging out error message.
Thank you

**Comment by vbaddi** [comment]
Closing this PR.
Adding logging information to multiple model loaders here [#4808](https://github.com/pytorch/glow/pull/4808)

**Pull request closed without merging**
