### PR TITLE
[Windows] Instructions to build Glow tools for win x86 using the MSYS environment

### PR DESCRIPTION
**Pull request by CristinaEnescu**
**Summary**
Add documentation with instructions to build Glow for Windows x86 using the MSYS MINGW environment.
This is oriented more towards delivering the Glow front-end tools (e.g. image-classifier) on the windows side for an out-of-the-box experience with Glow for Windows users (and not developers).
If users are happy with the user experience and functionality, they might become contributors (like myself).

**Documentation**
Added GlowWindowsBuildx86.md

**Fixes**
In order for the windows build to work some Cmake fixes were required.
Also the msys build signaled a warning in Type.h which is a potential bug (fixed that).

**Test Plan**
None. I guess you should try to follow the instructions and verify the build works.
You might also have a look on the compile warnings and see if there are some serious problems there (like I spotted the problem from Type.h).

**Proposal**
To reach more to end-users which are non-experts and want to give Glow a try using their Windows machine (very common case) using an out-of-the-box deliverable, I propose:

1. Automatize the windows build using the instructions I gave and insert the windows build as a stage in the CI pipeline. All that is required is a windows server on your side, setup the msys environment once, and run some automated script to build (the build itself takes only a couple of minutes)
2. Provide a link on the Glow front page to the latest Windows build (personally I would find that extremely useful - other might as well).

I attached a sketch of the bash script which does the build and package it. The package should also contain the "dot.exe" utility which I find extremely useful for converting the dot file generated with "-dump-graph-DAG" option to PDF for graph inspection with the command:
`dot -Tpdf graph.dot -o graph.pdf -Nfontname="Times New Roman,"`
[glow-build-win-x64.sh.txt](https://github.com/pytorch/glow/files/3743728/glow-build-win-x64.sh.txt)
The bash script can be called from the Windows cmd without entering the msys2 shell like this:
`C:/msys64/msys2_shell.cmd  -mingw64  -where C:/msys64/mingw64  -c "./glow-build-win-x64.sh"`
assuming the script is located in _C:/msys64/mingw64/glow-build-win-x64.sh_

### CODE REVIEW

**Comment by ayermolo** [comment]
You can just build glow on windows through regular command prompt/powershell.... 
But I guess with MingW it streamlines some parts.

**Comment by ayermolo** [comment]
FYI CI for windows issue: https://github.com/pytorch/glow/issues/2386

**Comment by CristinaEnescu** [comment]
But I cannot see in any Glow documentation how to do that:  instructions, how to build dependencies, etc. And in any case the windows build is not automatized: part of CI builds or provided directly as deliverable.

**Comment by ayermolo** [comment]
Yep you are right. 100% on me. Keep putting it off due to internal stuff taking priority. :) 
If/When this lands I can append to yours other way.

**Comment by nadavrot** [comment]
Alexander, thank you for doing this work.

**Comment by nadavrot** [comment]
@CristinaEnescu Thank you for doing this work!

**Comment by CristinaEnescu** [comment]
Any news on this? Can we have this merged?

**Comment by ayermolo** [comment]
@nadavrot can this be  reviewed/merged?
Thank You

**Comment by ayermolo** [comment]
@jfix71 Thanks!

**Pull request closed without merging**
