### PR TITLE
Zero-arithmetic and identity-arithmetic optimizations with uniform constant.

### PR DESCRIPTION
**Pull request by ksaurabh-cadence**
Summary:
Enhance zero-arithmetic and identity-arithmetic optimizations to include uniform constant.

Documentation:

[Optional Fixes #issue]

Test Plan:
Graph Optimizer Test aded
Please see a detailed explanation of how to fill out the fields in the relevant sections in PULL_REQUEST.md.

### CODE REVIEW

**Comment by saurabh-shandilya** [comment]
Depends on https://github.com/pytorch/glow/pull/4513

**Comment by ksaurabh-cadence** [comment]
> Nice, thanks! #4513 should be landing shortly, can you rebase off master once it does so CI is all green?

Rebased! Fingers crossed CI. Some tests might get affected because now constant will move to RHS for all binary ops.

**Comment by jfix71** [comment]
@ksaurabh-cadence FYI this was backed out in https://github.com/pytorch/glow/pull/4665 because it was causing some immediate issues for some important workloads for us. We didn't have time to track down the problem but hopefully can soon. Sorry for the inconvenience.

**Comment by ksaurabh-cadence** [comment]
@jfix71  A side effect of this change is that when constants (uniform/no-uniform) are present on the LHS of a binary arithmetic op it will be moved to the RHS. Could this be affecting something? 

Do I need to submit this again when the issue gets resolved or FB will take care of it?

**Comment by jfix71** [comment]
@ksaurabh-cadence Yeah, I'm wondering if it's a subtle issue with accumulation order or something, as the problem went away when `isConstant()` was not changed as in the PR. Would the PR be useful just without that constant swapping for now? That should be fine to land in the meantime if you'd prefer.

**Comment by ksaurabh-cadence** [comment]
@jfix71 Can this be merged as is, or do I need to create a new PR? Is the original problem because of which this had to be backed out, still there?

**Comment by jfix71** [comment]
@ksaurabh-cadence We are checking on our end if it's still a problem, I will get back to you soon. No need to do anything on your end, unless you want to change the PR I will land the exact same thing rebased.

**Pull request closed without merging**
