### PR TITLE
Fix compilation failure when GLOW_USE_PNG_IF_REQUIRED=OFF

### PR DESCRIPTION
**Pull request by sladwa**
Summary: Compilation fails when GLOW_USE_PNG_IF_REQUIRED=OFF. This PR addresses this problem.

Test Plan: Ninja test is run

### CODE REVIEW

**Comment by sladwa** [comment]
@jfix71 Kindly help to review the changes. Also let us know which CIRCLE_JOB should one add a build command with GLOW_USE_PNG_IF_REQUIRED=OFF so that in case someone breaks this feature it can be caught during CI testing?

**Comment by jfix71** [comment]
@sladwa Thanks for the fix. Looks like there's a conflict, need to rebase on master. RE: CI, I guess it could be added to DEBUG, but then we'd need to build+destroy+rebuild? Or could just add it to a new CI job, perhaps we should have one with different build configurations that don't run any tests, just make sure everything builds -- are there other build configurations you care about tracking?

**Comment by sladwa** [comment]
Hey @jfix71  have rebased the changes to master. I think it is better to have different CI job for these purpose which does only compilation.  After this change is accepted, does adding a new circle job in .circleci/build.sh is good enough and CI automation will run this new job ?

**Comment by jfix71** [comment]
> After this change is accepted, does adding a new circle job in .circleci/build.sh is good enough and CI automation will run this new job ?

Yes, that should be sufficient.

**Pull request closed without merging**
