### PR TITLE
Fixes a bug where LLVMIRGen::updateInlineAttributes() is clearing noalias parameter attributes (reopened #4889 with an additional fix.

### PR DESCRIPTION
**Pull request by andreas-hommel**
LLVMIRGen::updateInlineAttributes() currently clears all function attribute lists including the valuable “noalias” parameter attributes that were previously explicitly added in emitDataParallelKernelImpl(). This leads to suboptimal optimization, e.g., loop vectorization inserts explicit memory region overlap checks in the final binary code. This fix only clears the function attributes and leaves the return and parameter attributes unchanged. 

This causes failures in some regression tests, so there is an additional fix in isOverlappingWithAnyBundleBufferOperands() to prevent bundling of exactly overlapping buffers. This additional fix is necessary because the buffer pointers are now correctly "noalias" qualified, so the kernel operations can be reordered by LLVM's optimizations. This may result in smaller (but correct)  bundles, for the future we may want to investigate if removing "noalias" can be used to create bigger and faster bundles.

### CODE REVIEW

**Comment by opti-mix** [comment]
Hi @andreas-hommel,

I agree with your analysis of the issue. It is definitely related to the deallocations and reuse of buffers. 


> With this we may end up with fewer stacked kernels, 

Yes, this is a bit unfortunate.

> a better way to fix this could be to defer delallocations until a stacked kernel is generated. I can look into that if you agree with my analysis of this problem.

Deferring deallocations could be one possible solution. Another possible solution could be to detect the buffers that are aliasing and not add noalias for those specific buffers in the stacked kernels.

WDYT?

**Comment by andreas-hommel** [comment]
The buffers are not aliasing, at least not originally, the real bug is that stacking generates the deallocations before the operations (which deferred to the stacked kernel), so the stacked kernel operates on deallocated memory. So the "aliasing" is a side effect of operating on deallocated and reassigned memory. So deferring the deallocations as well is probably the cleanest solution (operating on freed memory may have other side effects).
I have tried a simple deferred dealloc implementation locally but that seems to cause failures in other CPUOperator tests, so there may be another (unrelated?) bug.

**Comment by opti-mix** [comment]
@andreas-hommel 

I've looked at your example again:

```
 5 %dequantize0 = dequantize @out %res0, @in %zero_res
  6 %dealloc_zero_res = deallocactivation @out %zero_res // size: 60
  7 %zero__1_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<4 x 15>} // size: 60 // Users: @in 11, @inout 9, @out 12, @out 8
  8 %zero__1 = splat @out %zero__1_res { Value: 0.000000e+00}
```

While it looks like zero_res and zero__1_res are not aliasing, I'm not sure it is quite the case. We have the memory allocation logic in `AllocationsInfo`, which tries to reuse memory to lower the peak memory consumption. Thus, I suspect that this example results in assigning the same memory offset/address to both zero_res and zero__1_res. If this is the case, our LLVM-based codegen will just follow the decisions of AllocationsInfo. `isOverlappingWithAnyBundleBufferOperands` actually checks if an operand overlaps with anything already in the bundle. But it has an interesting special case, where there is an exact overlap. I still think we cannot mark such an operand with an exact overlap as `noalias` basically.


> With this we may end up with fewer stacked kernels.

Yes. This may affect performance.

> a better way to fix this could be to defer delallocations until a stacked kernel is generated. 

To defer deallocations, I think you'd need to alter `AllocationsInfo`, as LLVMIRCodeGen does not decide about memory allocations on its own. And if you do change the logic there, you may eventually increase the peak memory consumption as you keep a buffer alive longer then before and do not reuse its memory. Plus, `AllocationsInfo` would probably need to know about stacking now.

**Comment by andreas-hommel** [comment]
Stacking essentially rewrites the code to this:

```
  5 %dequantize0 = dequantize @out %res0, @in %zero_res
  6 %dealloc_zero_res = deallocactivation @out %zero_res // size: 60
  7 %zero__1_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<4 x 15>} // size: 60 // Users: @in 11, @inout 9, @out 12, @out 8
  8 %zero__1 = splat @out %zero__1_res { Value: 0.000000e+00}

->

  5 %dealloc_zero_res = deallocactivation @out %zero_res // size: 60
  6 %zero__1_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<4 x 15>} // size: 60 // Users: @in 11, @inout 9, @out 12, @out 8
  7 %dequantize0 = stacked( dequantize @out %res0, @in %zero_res; splat @out %zero__1_res { Value: 0.000000e+00} )

```

Deallocating something before it is use is a programmer error, so I think this transformation is illegal and a bug in the current GLOW. My original fix simply preserves the "noalias" information that is explicit added when generating the kernel functions:

```
void LLVMIRGen::emitDataParallelKernelImpl(
    llvm::IRBuilder<> &builder, llvm::ArrayRef<const Instruction *> bundle,
    llvm::ArrayRef<llvm::Type *> argTypes,
    llvm::DenseMap<Value *, int> &bufferToArgNum,
    llvm::ArrayRef<llvm::Value *> buffers) {
...
  // Mark all kernel function buffer parameters as no-alias, because above
  // we ensured that they are uniqued.
  for (unsigned paramIdx = 0; paramIdx < bufferToArgNum.size(); ++paramIdx) {
    kernelFunc->addParamAttr(paramIdx, llvm::Attribute::AttrKind::NoAlias); <<<<
  }
…

```

and that allows more aggressive optimizations in LLVM exposing this otherwise hidden bug.

So I think the correct stacking rewrite would have been 

```
  5 %zero__1_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<4 x 15>} // size: 60 // Users: @in 11, @inout 9, @out 12, @out 8
  6 %dequantize0 = stacked( dequantize @out %res0, @in %zero_res; splat @out %zero__1_res { Value: 0.000000e+00} )
  7 %dealloc_zero_res = deallocactivation @out %zero_res // size: 60

```

i.e. use a deferred deallocation.

**Comment by opti-mix** [comment]
@andreas-hommel 

Thanks for your explanations. I'm still trying to better understand the root causes.

You say that stacking essentially rewrites the code into the form you presented. While this is true in terms of in which order the instructions are processed during LLVM code generation, it misses one important point IMHO. `allocactivation` and `deallocactivation` do not produce any LLVM IR code during LLVM code generation, e.g. they do not produce any allocas or something like that. They also do not even perform any kind of address assignments to buffers. So, effectively they are no-ops at the time when we generate LLVM IR. These two instructions are currently only used by the IROptimizer to perform some optimizations and later on by `AllocationsInfo` to perform *static* memory allocation. That is one big block of memory is allocated and each buffer being used by the Glow IR is assigned a position (i.e. offset) inside this big block of memory. `AllocationsInfo` tries to reuse the memory inside this memory block as much as possible and so it may assign the same address to different buffers as long as their lifetimes do not overlap (and this is decided by looking at allocations and deallocation IR instructions). After this stage, `allocactivation` and `deallocactivation` are effectively NOPs and we could even remove them from the IRFunction probably, unless we want to keep them for some debugging/verification reasons.

With the explanation above, do you still think that the problem is due to re-ordering of allocs/deallocs during the LLVM IR generation?

**Comment by andreas-hommel** [comment]
I am saying this without having looked at AllcationsInfo, but I assume that it is using allocactivation / deallocactivation to decide lifetimes overlap, so the allocation within that activation block is done at compile-time, but it is an allocation/deallocation.

If it not based on  allocactivation / deallocactivation it should have detected that the stacked kernel arguments (dequantize/splat) overlap and that they cannot reuse the same memory space.

**Comment by opti-mix** [comment]
@andreas-hommel Please have a look at `AllocationsInfo` first, if possible, so that we are on the same page in terms of understanding. The file is small and the logic there is rather simple. And yes, it is using allocactivation / deallocactivation to decide if lifetimes overlap. 

The problem is that `AllocationsInfo` is done way before LLVM IR generation and it is not even aware of the LLVM IR generation, because it is used also e.g. other non-LLVM based backends. LLVMIRCodeGen later on does a very aggressive bundling of instructions for stacking and breaks some invariants, as you describe. 

The solutions as we discussed are either to make the bundles smaller (i.e. never bundle IR instructions with overlapping intervals and use no-alias for all of the buffers) or detecting overlaps and marking only non-overlapping buffers no-alias.

**Comment by andreas-hommel** [comment]
I had another look at this, you are right the allocation happens before the merging, this is one of the failing tests:

```
function concatVectors
declare {
  %V = WeightVar float<4 x 5> mutable // size: 80 // Users: @in 1
  %res0 = WeightVar float<12 x 5> mutable // size: 240 // Users: @out 5
  %res1 = WeightVar float<4 x 15> mutable // size: 240 // Users: @out 11

  ; size = 560 bytes
}

code {
  0 %quantize_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<4 x 5>} // size: 20 // Users: @out 10, @in 9, @in 4, @out 1
  1 %quantize = quantize @out %quantize_res, @in %V
  2 %zero_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<12 x 5>} // size: 60 // Users: @in 5, @inout 4, @out 6, @out 3
  3 %zero = splat @out %zero_res { Value: 0.000000e+00}
  4 %tile0__1__1 = inserttensor @inout %zero_res, @in %quantize_res { Offsets: [0, 0], Count: 3, Axis: 0}
  5 %dequantize0 = dequantize @out %res0, @in %zero_res
  6 %dealloc_zero_res = deallocactivation @out %zero_res // size: 60
  7 %zero__1_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<4 x 15>} // size: 60 // Users: @in 11, @inout 9, @out 12, @out 8
  8 %zero__1 = splat @out %zero__1_res { Value: 0.000000e+00}
  9 %tile1__1__1 = inserttensor @inout %zero__1_res, @in %quantize_res { Offsets: [0, 0], Count: 3, Axis: 1}
  10 %dealloc_quantize_res = deallocactivation @out %quantize_res // size: 20
  11 %dequantize1 = dequantize @out %res1, @in %zero__1_res
  12 %dealloc_zero__1_res = deallocactivation @out %zero__1_res // size: 60
}
Allocated activation zero_res size: 60  address range:  [64, 124]
Allocated activation quantize_res size: 20  address range:  [0, 20]
Allocated activation zero__1_res size: 60  address range:  [64, 124]

```

The problem is that zero_res ad zero__1_res get allocated to the same address and they have the same size. The merging happens because this function

```
static bool isOverlappingWithAnyBundleBufferOperands(
    AllocationsInfo &allocationsInfo,
    llvm::SmallVectorImpl<const Instruction *> &bundle, Value *buf) {
  auto addr1 = allocationsInfo.allocatedAddress_[buf];
  auto size1 = buf->getSizeInBytes();
  for (auto bi : bundle) {
    for (auto bop : bi->getOperands()) {
      auto buf2 = bop.first;
      auto addr2 = allocationsInfo.allocatedAddress_[buf2];
      auto size2 = buf2->getSizeInBytes();
      // It is fine, if buffers of different data-parallel instructions are
      // allocated exactly the same memory region.
      if (addr1 == addr2 && size1 == size2) {
        continue;   <<<<<<<<< AH: why is this fine?
      }
      if ((addr1 >= addr2 && addr1 < addr2 + size2) ||
          (addr2 >= addr1 && addr2 < addr1 + size1)) {
        // Two intervals overlap, but are not the same.
        return true;
      }
    }
  }
  return false;
}

```
returns “false”. So I think the real bug is that “addr1 == addr2 && size1 == size2” should really return “true”. I am not sure why one would treat a perfect complete overlap different from a partial overlap.

**Comment by andreas-hommel** [comment]
I got pinged by the stale-bot, anyone still looking at this?

**Comment by jfix71** [comment]
@andreas-hommel I think this was just delayed due to holidays, I'm assuming @opti-mix will be handling this still.

**Comment by opti-mix** [comment]
@andreas-hommel Sorry for a late response. I was taking some days off during holidays.

> I am not sure why one would treat a perfect complete overlap different from a partial overlap.

The original idea was to enable as much memory reuse as possible. And handling a perfect overlap allowed for longer bundles (i.e. with more instructions) at the expense of making **some of the buffers** used by the stacked kernel alias with each other. 

You proposed fix makes sure that **no operand buffers** used in a stacked ever alias. This is the positive effect. The negative effect could be that the bundles may get shorter as a result of this.

An alternative fix would be to mark those "perfectly overlapping operand buffers" as aliasing and the rest of operand buffers used by a bundle as non-aliasing. WDYT?

I don't have a very strong opinion about this. Ideally, it would be good to see if your fix makes bundles shorter in many cases. But for the time being I think your fix could be fine. BTW, could you add an elaborative comment in isOverlappingWithAnyBundleBufferOperands explaining pros and cons of considering such perfectly overlapping buffers to be part of bundles or prohibiting this.

**Comment by andreas-hommel** [comment]
> I don't have a very strong opinion about this. Ideally, it would be good to see if your fix makes bundles shorter in many cases. But for the time being I think your fix could be fine. BTW, could you add an elaborative comment in isOverlappingWithAnyBundleBufferOperands explaining pros and cons of considering such perfectly overlapping buffers to be part of bundles or prohibiting this.

I agree, ideally we would check if this impacts performance. In my local test NNs it did not result in smaller kernel bundles, but the improved noalias handling did really help :-). SO I think this make GLOW better, but I have added a comment and a TODO note.

**Comment by opti-mix** [comment]
@andreas-hommel Thanks. Looks good now. Could you update PR message at the top to be a shorter summary of what this PR does? When I import it into FB version control it copies the whole message as the commit message, which looks pretty ugly ;-)

**Comment by andreas-hommel** [comment]
Original PR message for reference:

Sorry that this took so long, but I finally found the time to investigate this. I believe that my fix is correct, it simply exposes another bug in the code that generates data parallel kernels.

This is the original fix:

> LLVMIRGen::updateInlineAttributes() currently clears all function attribute lists including the valuable noalias parameter attributes that were previously added. This leads to suboptimal optimization, e..g, loop vectorization inserts explicit memory region overlap checks in the final binary code
> 
> I suggest making this change to only clear the function attributes and leave the return and parameter attributes alone.
> 
> A better fix would be to only remove the unwanted target-specific machine code function attributes, but that would require more work, esp. to identify what is wanted (inline/noinline) what is not .
> 

This caused failure in some tests, so here is a fix for another bug that was exposed by my (other wise correct) fix:

One of the tests that fails is:

```
TEST_P(OperatorTest, QuantizedTile) {
  CHECK_IF_ENABLED();

  F_->setName("concatVectors");

  auto *V = mod_.createPlaceholder(ElemKind::FloatTy, {4, 5}, "V", false);
  bindings_.allocate(V);

  auto quantizationParams =
      glow::quantization::chooseQuantizationParams({0, 20});
  auto quantizeTy =
      mod_.uniqueType(ElemKind::Int8QTy, {4, 5}, quantizationParams.scale,
                      quantizationParams.offset);
  auto *Q = F_->createQuantize("quantize", V, quantizeTy);

  Node *T0 = F_->createTile("tile0", Q, /* tiles */ 3, /* axis */ 0);
  auto *DQ0 = F_->createDequantize("dequantize0", T0, ElemKind::FloatTy);
  auto *result0 = F_->createSave("res0", DQ0);
  bindings_.allocate(result0->getPlaceholder());

  Node *T1 = F_->createTile("tile1", Q, /* tiles */ 3, /* axis */ 1);
  auto *DQ1 = F_->createDequantize("dequantize1", T1, ElemKind::FloatTy);
  auto *result1 = F_->createSave("res1", DQ1);
  bindings_.allocate(result1->getPlaceholder());

  Tensor VT(ElemKind::FloatTy, {4, 5});

  for (dim_t i = 0; i < 4; i++) {
    for (dim_t j = 0; j < 5; j++) {
      VT.getHandle<float>().at({i, j}) = i * 5 + j;
    }
  }
…
```

This ends up as:

```
Ir after pass IRVerify
function concatVectors
declare {
  %V = WeightVar float<4 x 5> mutable // size: 80 // Users: @in 1
  %res0 = WeightVar float<12 x 5> mutable // size: 240 // Users: @out 5
  %res1 = WeightVar float<4 x 15> mutable // size: 240 // Users: @out 11

  ; size = 560 bytes
}

code {
  0 %quantize_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<4 x 5>} // size: 20 // Users: @out 10, @in 9, @in 4, @out 1
  1 %quantize = quantize @out %quantize_res, @in %V
  2 %zero_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<12 x 5>} // size: 60 // Users: @in 5, @inout 4, @out 6, @out 3
  3 %zero = splat @out %zero_res { Value: 0.000000e+00}
  4 %tile0__1__1 = inserttensor @inout %zero_res, @in %quantize_res { Offsets: [0, 0], Count: 3, Axis: 0}
  5 %dequantize0 = dequantize @out %res0, @in %zero_res
  6 %dealloc_zero_res = deallocactivation @out %zero_res // size: 60
  7 %zero__1_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<4 x 15>} // size: 60 // Users: @in 11, @inout 9, @out 12, @out 8
  8 %zero__1 = splat @out %zero__1_res { Value: 0.000000e+00}
  9 %tile1__1__1 = inserttensor @inout %zero__1_res, @in %quantize_res { Offsets: [0, 0], Count: 3, Axis: 1}
  10 %dealloc_quantize_res = deallocactivation @out %quantize_res // size: 20
  11 %dequantize1 = dequantize @out %res1, @in %zero__1_res
  12 %dealloc_zero__1_res = deallocactivation @out %zero__1_res // size: 60
}

```
The IR that is generated for the first dequantization (with my fix) is:

```
; Function Attrs: noinline
define internal void @libjit_stacked_kernel.2_3_specialized(float* noalias, i8* noalias, i8* noalias) #8 {
entry:
  br label %loop

loop:                                             ; preds = %loop, %entry
  %3 = phi i64 [ 0, %entry ], [ %nextvar, %loop ]
  %4 = call float @libjit_element_dequantize_kernel_f(i64 %3, i8* %1, float 0x3FB4141420000000, i32 -128)
  %buffer.element.addr = getelementptr float, float* %0, i64 %3
  store float %4, float* %buffer.element.addr
  %5 = call i8 @libjit_splat_kernel_i8(i64 %3, i8 -128, i8* null, i8* null)
  %buffer.element.addr1 = getelementptr i8, i8* %2, i64 %3
  store i8 %5, i8* %buffer.element.addr1
  %nextvar = add nuw nsw i64 %3, 1
  %loopcond = icmp ult i64 %nextvar, 60
  br i1 %loopcond, label %loop, label %afterloop, !llvm.loop !4

afterloop:                                        ; preds = %loop
  ret void
}

```
Note that all pointer arguments are noalias qualified by this loop

```
  // Mark all kernel function buffer parameters as no-alias, because above
  // we ensured that they are uniqued.
  for (unsigned paramIdx = 0; paramIdx < bufferToArgNum.size(); ++paramIdx) {
    kernelFunc->addParamAttr(paramIdx, llvm::Attribute::AttrKind::NoAlias);
  }

```
With my fix these qualifiers are not dropped. It appears that %1 and %2 refer to the same array, the elements are dequantized and then cleared (libjit_splat_kernel_i8). However, since the pointers are noalias qualified LLVM optimize this to:

```
define internal fastcc void @libjit_stacked_kernel.2_3_specialized(float* noalias nocapture, i8* noalias nocapture readonly, i8* noalias nocapture) unnamed_addr #4 {
entry:
  tail call void @llvm.memset.p0i8.i64(i8* align 1 %2, i8 -128, i64 60, i1 false)
  %3 = bitcast i8* %1 to <8 x i8>*
  %wide.load = load <8 x i8>, <8 x i8>* %3, align 1
  %4 = sext <8 x i8> %wide.load to <8 x i32>
  %5 = add nsw <8 x i32> %4, <i32 128, i32 128, i32 128, i32 128, i32 128, i32 128, i32 128, i32 128>
  %6 = sitofp <8 x i32> %5 to <8 x float>
  %7 = fmul reassoc nsz arcp contract <8 x float> %6, <float 0x3FB4141420000000, float 0x3FB4141420000000, float 0x3FB4141420000000, float 0x3FB4141420000000, float 0x3FB4141420000000, float 0x3FB4141420000000, float 0x3FB4141420000000, float 0x3FB4141420000000>
  %8 = bitcast float* %0 to <8 x float>*
  store <8 x float> %7, <8 x float>* %8, align 4
  %9 = getelementptr inbounds i8, i8* %1, i64 8

```
The bug is in generateLLVMIRForModule() where dequantize(5) and splat(8) are merged into one kernel:  

```
  5 %dequantize0 = dequantize @out %res0, @in %zero_res
  6 %dealloc_zero_res = deallocactivation @out %zero_res // size: 60
  7 %zero__1_res = allocactivation  { Ty: i8[S:0.078431375 O:-128][0.000,20.000]<4 x 15>} // size: 60 // Users: @in 11, @inout 9, @out 12, @out 8
  8 %zero__1 = splat @out %zero__1_res { Value: 0.000000e+00}

```
The problem with that is that %zero_res is deallocated and the reused by the next allocation and we end up with this broken code:

```
; Function Attrs: alwaysinline nounwind
define i32 @jitmain(i8* nocapture readnone, i8*, i8*) local_unnamed_addr #1 {
entry:
  %3 = ptrtoint i8* %2 to i64
  %4 = ptrtoint i8* %1 to i64
  %5 = bitcast i8* %1 to float*
  tail call fastcc void @libjit_stacked_kernel_0_specialized(i8* %2, float* %5) #6
  %6 = add i64 %3, 64
  %7 = inttoptr i64 %6 to i8*
  tail call fastcc void @libjit_stacked_kernel.1_1_specialized(i8* %7) #6
  tail call fastcc void @libjit_insert_tensor_i8_2_specialized(i8* %7, i8* %2) #6
  %8 = add i64 %4, 128
  %9 = inttoptr i64 %8 to float*
  tail call fastcc void @libjit_stacked_kernel.2_3_specialized(float* %9, i8* %7, i8* %7) #6
  tail call fastcc void @libjit_insert_tensor_i8_4_specialized(i8* %7, i8* %2) #6
  %10 = add i64 %4, 384
  %11 = inttoptr i64 %10 to float*
  tail call fastcc void @libjit_stacked_kernel.3_5_specialized(float* %11, i8* %7) #6
  ret i32 0
}

```
where %7 is cleared and dequantized with one kernel.

The fix is to not stack kernels across deallocations, see LLVMIRGEn.cpp fix.

With that we get

```
; Function Attrs: alwaysinline nounwind
define i32 @jitmain(i8* nocapture readnone, i8*, i8*) local_unnamed_addr #1 {
entry:
  %3 = ptrtoint i8* %2 to i64
  %4 = ptrtoint i8* %1 to i64
  %5 = bitcast i8* %1 to float*
  tail call fastcc void @libjit_stacked_kernel_0_specialized(i8* %2, float* %5) #6
  %6 = add i64 %3, 64
  %7 = inttoptr i64 %6 to i8*
  tail call fastcc void @libjit_stacked_kernel.1_1_specialized(i8* %7) #6
  tail call fastcc void @libjit_insert_tensor_i8_2_specialized(i8* %7, i8* %2) #6
  %8 = add i64 %4, 128
  %9 = inttoptr i64 %8 to float*
  tail call fastcc void @libjit_stacked_kernel.2_3_specialized(float* %9, i8* %7) #6
  tail call fastcc void @libjit_stacked_kernel.3_4_specialized(i8* %7) #6
  tail call fastcc void @libjit_insert_tensor_i8_5_specialized(i8* %7, i8* %2) #6
  %10 = add i64 %4, 384
  %11 = inttoptr i64 %10 to float*
  tail call fastcc void @libjit_stacked_kernel.4_6_specialized(float* %11, i8* %7) #6
  ret i32 0
}

```

and all tests pass.

With this we may end up with fewer stacked kernels, a better way to fix this could be to defer delallocations until a stacked kernel is generated. I can look into that if you agree with my analysis of this problem.

**Comment by andreas-hommel** [comment]
> @andreas-hommel Thanks. Looks good now. Could you update PR message at the top to be a shorter summary of what this PR does? When I import it into FB version control it copies the whole message as the commit message, which looks pretty ugly ;-)

Done, it would be a pretty ugly and long commit message :-)

**Pull request closed without merging**
