### PR TITLE
[IR] Improve run time of IR buffer sharing optimization pass.

### PR DESCRIPTION
**Pull request by geoffberry**
Summary:
Use a single IRBuilder for the entire buffer sharing pass instead of
constructing one for each buffer replacement since the IRBuilder
destructor does a full walk of the instruction list.

Documentation:

Test Plan:
Validated on CPUOperatorTest

### CODE REVIEW

**Comment by opti-mix** [comment]
@geoffberry Nice catch! The approach looks good.

Quick suggestions: Most of the affected methods are inside the BufferSharingOptimizer class. You could pass IRBuilder as a constructor argument. This way you don't need to pass it around as an explicit argument to methods inside this class.

**Comment by geoffberry** [comment]
Hi @opti-mix I've updated the change based on your suggestion.

**Comment by opti-mix** [comment]
LGTM!

**Comment by opti-mix** [comment]
Out of curiosity: Was it causing long compile-time delays on real use-cases? Or is this fix more of a theoretical concern?

**Review by opti-mix — APPROVED** [review]

**Comment by geoffberry** [comment]
> Out of curiosity: Was it causing long compile-time delays on real use-cases? Or is this fix more of a theoretical concern?

This was causing a very long compile-time on a real network with a lot of buffer sharing opportunities.

**Pull request closed without merging**
