### PR TITLE
[WIP]Full fp16 interpreter

### PR DESCRIPTION
**Pull request by qcolombet**
*Description*:
This PR implements the missing pieces for fp16 support in the interpreter to support all the operators used in inference.

*Testing*:
TODO, thus WIP.

### CODE REVIEW

**Comment by qcolombet** [comment]
The first commit that extends float16 with the missing operators is track in #1930.

**Comment by jfix71** [comment]
Oh just realized it's WIP -- ignore me 😄

**Comment by qcolombet** [comment]
Thanks for taking a stab at it @jfix71.
I was mainly missing the tests so your feedback are already useful!

Good point for the static_assert, I forgot to add those this time :S. I am not sure I can push them in the macro though, since it has to be in the templated function itself.

**Comment by jfix71** [comment]
Hmm, I was assuming the preprocessor would put them in the correct location before the static assert is checked.

**Comment by nadavrot** [comment]
Nice!

**Comment by qcolombet** [comment]
> Hmm, I was assuming the preprocessor would put them in the correct location before the static assert is checked.

Re-reading what you were saying, we were talking about something different :). You're right a new macro to insert the static_assert would do the trick (as opposed to extending the one that I added, which is what I thought you were suggesting).

**Comment by nadavrot** [comment]
This PR looks really good. Is this blocked on anything?

**Comment by qcolombet** [comment]
I want to double check what I was saying in my last comment: we can create fp16 variant of all the nodes.

**Comment by qcolombet** [comment]
The only problematic create methods (they hardcode FloatTy) are:
GRU
SimpleRNN
LSTM
rowwiseQuantizedFC
quantizationProfile
Dequantize

We probably don't need quantization support on fp16, at least for now and the complex nodes (GRU, SimpleRNN, LSTM) can be expanded into simpler ones, so strictly speaking we are not block here.

We'll add those as we need. Therefore, I am going to coming this one as is.

**Pull request merged**
