### PR TITLE
[quantization/optimizations] Remove redundant Rescale after Slice.

### PR DESCRIPTION
**Pull request by rdzhabarov**

### CODE REVIEW

**Comment by nadavrot** [comment]
The code looks really good. Simple and elegant.

**Comment by rdzhabarov** [comment]
Unfortunately, there is a fundamental problem which I sort of touched in https://github.com/pytorch/glow/pull/979 (and I have not fully realized until now)
The problem is that I cannot simply remove RescaleNode, I need to recreate the next node as well.
For example, Slice -> Rescale -> Reshape. Now after removing of Rescale, Reshape node is in an invalid state as it has different scales for inputs and outputs. Another example would be if Rescale -> Concat and for Concat, we expect all of the inputs have the same {S,O} cannot simply remove Rescale.
As I outlined in the PR/979 we could go this way, but there is going to be huge switch on recreating all nodes after Rescale and also taking into considerations situations where Rescale cannot be removed.

I think it's worthwhile to pursue the 979 approach at the moment.

**Comment by rdzhabarov** [comment]
As discussed offline we'll introduce sink of the RescaledNode down the chain as well as combining Rescale with certain operations like MatMul and other arithmetic operations. In nature, it's going to be similar to FUSE of Rescale we do now.
Having this optimization in place will allow covering a wider range of optimizations comparing to fixing profiling data as suggested in https://github.com/pytorch/glow/pull/979

**Comment by rdzhabarov** [comment]
More generic handling: https://github.com/pytorch/glow/pull/998

**Pull request closed without merging**
