### PR TITLE
[fix] Fix internal build.

### PR DESCRIPTION
**Pull request by rdzhabarov**
*Description*:
Fix fbcode build with the latest Glow.

*Testing*:
CI

*Documentation*:
n/a

### CODE REVIEW

**Comment by opti-mix** [comment]
@rdzhabarov `FACEBOOK_INTERNAL` is very fluffy. What will happen when FB updates the internal LLVM  to use e.g. LLVM >= 8?

Does `FACEBOOK_INTERNAL` has any kind of reasonable value, like 6 or 7 (reflecting which LLVM is used), which could be used for more precise checks?

**Comment by jackm321** [comment]
fyi the `RELEASE_WITH_EXPENSIVE_TESTS` should be fixed for real (hopefully) this time with #2576

**Comment by rdzhabarov** [comment]
> @rdzhabarov FACEBOOK_INTERNAL is very fluffy. What will happen when FB updates the internal LLVM to use e.g. LLVM >= 8?

> Does FACEBOOK_INTERNAL has any kind of reasonable value, like 6 or 7 (reflecting which LLVM is used), which could be used for more precise checks?

Agreed. It's not very transparent, but something that was used before (see other entries of that).
I'll see if we can eliminate that entirely.

**Comment by bertmaher** [comment]
> What will happen when FB updates the internal LLVM to use e.g. LLVM >= 8?

Internally when the LLVM team wants to update, they run the update on CI, look at what fails, and then harass all the service owners to update their stuff (last time it happened to be me oncall :) ).  Unfortunately our internal build does not neatly correspond to any released LLVM, or at least it didn't several months ago.

> Does FACEBOOK_INTERNAL has any kind of reasonable value, like 6 or 7 (reflecting which LLVM is used), which could be used for more precise checks?

There's an LLVM_PATCH_VERSION that FB sets according to its own whims, but AFAIK it's not tied to anything meaningful in the outside world.

**Comment by rdzhabarov** [comment]
There is a mix of LLVM versions used, I see both 7 and 8.0.20181009svn.

The fix above is required to run on both. Since updates are not really frequent and internal packages might be different I think keeping FB_INTERNAL seems a plausible solution.

@opti-mix let me know.

**Pull request merged**
