### PR TITLE
v0.4.0.0 Update for the Intel NNPI Backend

### PR DESCRIPTION
**Pull request by jsubag**
Summary: v0.4.0.0 Update for the Intel NNPI Backend

### CODE REVIEW

**Comment by jsubag** [comment]
@jfix71 , @arunm-git Please take a look.

**Comment by arunm-git** [comment]
Hi Jacob,
Changes here look fine, but some general questions:
* I'm guessing this PR requires the 0.4.0 drop  to work? (i.e. - we can't take this PR in isolation without moving to the 0.4.0 drop)? If so, we'll wait on this PR till we update nnpi-sw internally.
* BlockStream.cpp: the changes in this PR are fine. While reading the code in that file, I noticed that there may be a bug in allocateBlocks() where we update 'available' and return that new value even when the allocation fails. Mentioning it so we can address that (in a different PR is fine), and also fix the typos (*Offest instead of *Offset).

**Comment by jsubag** [comment]
CC: @omromano

**Comment by jsubag** [comment]
@arunm-git You're correct on both points - good catch.
I'll update the PR shortly

**Pull request closed without merging**
