### PR TITLE
32b dim_t fixes + a new builder for 32b dim t

### PR DESCRIPTION
**Pull request by pjaaskel**
Summary:

There were a few remaining 32b dim_t issues in recent code. E.g. one case of wrong vector initialization in the onnximporter/exporter.

Also adds a new circleci test for 32B_DIM_T that also builds the OpenCL backend to catch most of the size_t/64b assumed index code additions first hand. 

Test Plan:

Tested with LLVM7 64b/32b and pocl 64b/32b.

### CODE REVIEW

**Comment by bertmaher** [comment]
What is dim32/sparseToDense.onnxtxt?  It causes onnxExporterTest to fail, because it tries to load the dim32 directory as an onnx protobuf...

**Comment by pjaaskel** [comment]
> What is dim32/sparseToDense.onnxtxt? It causes onnxExporterTest to fail, because it tries to load the dim32 directory as an onnx protobuf...

It's a 32b index version of that model. How can I reproduce the fail? It doesn't fail for me by default.

**Comment by bertmaher** [comment]
Weird, the test fails using the FB-internal build system, but not with cmake.  This is probably something I just need to solve on our end.  Sorry for the confusion.

**Comment by bertmaher** [comment]
I did the merge internally to fix the OnnxExporter issues; landed as d09a273

**Pull request closed without merging**
