### PR TITLE
Simplify worker thread loop

### PR DESCRIPTION
**Pull request by bertmaher**
Summary:
- Use the idiomatic predicate version of cv.wait while waiting on the work queue.
- Avoid checking shouldStop_ while not holding lock.
- Trim some comment verbosity.

Test Plan: ThreadPoolTest, ThreadPoolExecutorTest

### CODE REVIEW

**Comment by rdzhabarov** [comment]
@bertmaher could you do "assignees". In that case it's clearly visible from https://github.com/pytorch/glow/pull page.

**Comment by bertmaher** [comment]
Sure!  It's weird that there's a separate "request" and "assign", I thought they were the same concept!

**Comment by nickgg** [comment]
Uh, I'm not following that problem @rdzhabarov:
* shouldStop_ is atomic.
* bool read/writes are sequentially consistent on x86.
* writing to shouldStop_ is done only under the lock anyway, and always triggers the cv event.

Don't really see what harm the comments were doing here as well.

**Comment by rdzhabarov** [comment]
> shouldStop_ is atomic.

if it's atomic it's ok. There is no reason for that to be atomic as we do writes/reads under workQueueMtx_ locked.

**Comment by bertmaher** [comment]
There wasn't actually a bug with `shouldStop_`, but it felt a bit fishy.  Regardless of atomicity it needs to be checked inside a critical section (like you said) so that it won't miss a wakeup.  Given that I don't see a point in doing an unlocked check of shouldStop - I guess it slightly optimizes the shutdown path?

**Comment by bertmaher** [comment]
Re: the comments, I mean, maybe I should leave well enough alone, but things like
```
// Lock the lock.
lock.lock()
```
don't seem like they actually clarify anything, since they more-or-less repeat that code.  At a glance all the verbosity seemed like a signal that something tricky was going on, when in fact it's just a pretty standard work dispatch loop.

**Comment by bertmaher** [comment]
Anyways, whatever.  This change isn't really necessary anyways.

**Pull request closed without merging**
