### PR TITLE
[Importer] Enable constant folding by default and extra fix.

### PR DESCRIPTION
**Pull request by mciprian13**
**Summary**
- Fix for #3827.
- Enable the constant folding by default.

**Documentation**
None

**Test Plan**
None

### CODE REVIEW

**Comment by mciprian13** [comment]
@jfix71 
It seems the text translator model fails if the constant folding is enabled with the attached error:
[build_54728_step_106_container_0.txt](https://github.com/pytorch/glow/files/4076404/build_54728_step_106_container_0.txt)
Namely:
`Unsupported node found while compiling Function eval_const_fold__ for backend Interpreter: ScatterData
`
If my understanding is correct, the constant folding fails with error if the node cannot be folded (not supported by Interpreter).
In my opinion, the constant folding should be interpreted as a best-effort optimization and therefore the model compilation should **NOT fail if a node cannot be folded** (at most a notification should be printed in the console) but the compilation should continue without folding that node.
What do you think?

**Comment by jfix71** [comment]
>In my opinion, the constant folding should be interpreted as a best-effort optimization and therefore the model compilation should NOT fail if a node cannot be folded (at most a notification should be printed in the console) but the compilation should continue without folding that node.

@mciprian13 Yeah I agree. I'm a bit confused as to how this has occurred, as I believe the Interpreter supports all the ops in this model. Regardless, please file an issue for this, it shouldn't be so hard to create a fix.

**Comment by mciprian13** [comment]
@jfix71 I created an issue for the point discussed above.

**Comment by jfix71** [comment]
I'm merging https://github.com/pytorch/glow/pull/4050 and https://github.com/pytorch/glow/pull/4061 into this PR when it lands in a bit, as it needed some fixes based on internal CI.

**Comment by Verma-Rajat** [comment]
quantization flows are broken due to this commit.
https://github.com/pytorch/glow/issues/4188

**Pull request closed without merging**
