### PR TITLE
[Importer] Fix bug with default min values in Clip operator.

### PR DESCRIPTION
**Pull request by balaram-cadence**
Summary:
min and max values are optional and might not be supplied for Clip operator. Import Clip operator with default min and max values when they are not provided.
Documentation:

[Optional Fixes #issue]

Test Plan:

Added ONNXImporterTest

### CODE REVIEW

**Review by yinghai — APPROVED** [review]
LGTM

**Comment by yinghai** [comment]
Can you audit the test errors?

**Comment by balaram-cadence** [comment]
> Can you audit the test errors?

Thanks for the review. The test failures seem to be unrelated to the pull request. I'll check again. 
Is there a way to re-run the failing jobs? I've seen InterpreterHostManagerTest failing intermittently due to asan(after passing repeatedly). I'm not sure if this is a known issue.

**Comment by balaram-cadence** [comment]
@yinghai, I have updated the patchset that fixes the asan issues. The changes are unrelated to this pull request, so please let me know if you want me to create separate pull request.

**Pull request closed without merging**
