### PR TITLE
Add support for Convert from Bool to Int32 in Interpreter and CPU backends.

### PR DESCRIPTION
**Pull request by aturetsk**
Author: Jun Bum Lim <junlim@cadence.com>

Summary:
Add support for Convert from Bool to Int32 in Interpreter and CPU backends.

Documentation:
N/A

Test Plan:
Extended operator unit test.

### CODE REVIEW

**Review by jfix71 — CHANGES_REQUESTED** [review]
LGTM -- but need to update OpenCLOperatorTest blacklist

**Comment by aturetsk** [comment]
Thanks for review! Disabled the test for OpenCL backend.

**Review by jfix71 — APPROVED** [review]
Thanks!

**Comment by aturetsk** [comment]
@jfix71, this and a couple of my other approved PRs are failing some Facebook internal regressions I have no access to. Any action from my side to help them land?

**Comment by jfix71** [comment]
@aturetsk Nope, I'll fix on my side, hopefully will land in the next 24 hours.

**Pull request closed without merging**
