### PR TITLE
Update for recent marvell.png

### PR DESCRIPTION
**Pull request by MNGanesan**
Summary:

Marvell.png  has been updated with latest Marvell logo

Documentation:

NA

[Optional Fixes #issue] NA

Test Plan:

NA

### CODE REVIEW

**Comment by Carrussalgreencompany** [comment]
Thank you for your response.Compliment of the season to you and your ***@***.***
    On Tuesday, January 3, 2023, 12:04:50 AM GMT+8, Facebook Community Bot ***@***.***> wrote:  
 
 


Hi @MNGanesan!

Thank you for your pull request and welcome to our community.

Action Required

In order to merge any pull request (code, docs, etc.), we require contributors to sign our Contributor License Agreement, and we don't seem to have one on file for you.

Process

In order for us to review and merge your suggested changes, please sign at https://code.facebook.com/cla. If you are contributing on behalf of someone else (eg your employer), the individual CLA may not be sufficient and your employer may need to sign the corporate CLA.

Once the CLA is signed, our tooling will perform checks and validations. Afterwards, the pull request will be tagged with CLA signed. The tagging process may take up to 1 hour after signing. Please give it that time before contacting us about it.

If you have received this in error or have any questions, please contact us at ***@***.*** Thanks!

**Comment by Carrussalgreencompany** [comment]
Good to hear from you.
Thank you for your response.

**Comment by opti-mix** [comment]
@MNGanesan Thanks for provided the updated logo. Could you please change its size to be similar to the old one or other logos on our home page? Otherwise it looks disproportionally big compared to others ;-) Thanks!

**Comment by MNGanesan** [comment]
Hi Roman,
Updated with size optimized logo and submitted PR
https://github.com/pytorch/glow/pull/6056



Thanks,Ganesan
 

    On Friday, 17 February 2023 at 00:15:00 GMT+5:30, Roman L ***@***.***> wrote:  
 
 


@MNGanesan Thanks for provided the updated logo. Could you please change its size to be similar to the old one or other logos on our home page? Otherwise it looks disproportionally big compared to others ;-) Thanks!

**Comment by MNGanesan** [comment]
Hi Roman,
After submitting my PR, I see some build failure.
Looks my change is only on .PNG logo file but not in the source files, I've no clue why these failures are, Please put some light on it.
Thanks,Ganesan
 

    On Sunday, 19 February 2023 at 21:20:23 GMT+5:30, M N Ganesan ***@***.***> wrote:  
 
 Hi Roman,
Updated with size optimized logo and submitted PR
https://github.com/pytorch/glow/pull/6056



Thanks,Ganesan
 

    On Friday, 17 February 2023 at 00:15:00 GMT+5:30, Roman L ***@***.***> wrote:  
 
 


@MNGanesan Thanks for provided the updated logo. Could you please change its size to be similar to the old one or other logos on our home page? Otherwise it looks disproportionally big compared to others ;-) Thanks!

**Pull request closed without merging**
