### PR TITLE
[GraphOptz] Remove identity Clip and Relu

### PR DESCRIPTION
**Pull request by mciprian13**
**Summary**
- Add graph optimization to remove **quantized** Clip and Relu nodes which are nops (identity). This happens when the min/max of the quantized range matches the min/max parameter of the Relu/Clip. For example the following is a Clip node which fits this description:
image

**Test Plan**
Unit tests added in GraphOptzTest.

### CODE REVIEW

**Comment by mciprian13** [comment]
ping

**Review by jfix71 — APPROVED** [review]
LGTM -- commented on #5729 as well.

**Comment by jfix71** [comment]
I can't import until you resolve the conflict, apologies. Can you rebase and I'll import/land? Thanks @mciprian13 !

**Comment by mciprian13** [comment]
@jfix71 I solved the conflicts. Have another look. Thanks!

**Pull request closed without merging**
