### PR TITLE
[Importer] Use addNodeAsOutput function to the save outputs code for each operator

### PR DESCRIPTION
**Pull request by beicy**

### CODE REVIEW

**Comment by beicy** [comment]
@jfix71  Yes, the run.sh works.

**Comment by rdzhabarov** [comment]
@beicy I think "dropout", "squezee" could also be changed accordingly. Could you fix those and check there are no more cases to clean up?

**Comment by beicy** [comment]
@rdzhabarov Thanks for pointing out the missing ones. I will double check it.

**Comment by rdzhabarov** [comment]
also, nit, there comments "// Save the outputs:" which seem useless.
It's better to have a method name such that it self-explanatory so you do not have to place comments on it.

**Pull request merged**
