### PR TITLE
[onnx loaders] Support Gather ops in onnxifi loader.

### PR DESCRIPTION
**Pull request by rdzhabarov**
*Description*:
Add common support for Gather/BatchGather

*Testing*:
Unit tests

*Documentation*:
n/a

cc: @yinghai

### CODE REVIEW

**Comment by yinghai** [comment]
Something like this: 
https://github.com/pytorch/glow/blob/bafda001779527fdde6cf4d5b62b7e75e71ccb7a/lib/Importer/ONNXIFIModelLoader.cpp#L196-L198

**Comment by rdzhabarov** [comment]
> ONNXIFIModelLoader::parseOperators too

yup!

**Comment by yinghai** [comment]
Please add a unit test if possible, too. :)

**Comment by rdzhabarov** [comment]
> Will be better with unit test.

that's the plan, see description for testing ;)

**Pull request merged**
