### PR TITLE
[opencl ci] Compile Glow with OpenCL and run some unit tests on CI.

### PR DESCRIPTION
**Pull request by rdzhabarov**
*Description*:
Add an option to compile with OpenCL support but do not run tests.
This is a first step to enable catching issues with OpenCL.

No major changes in build CI time for/after this PR.

See https://github.com/pytorch/glow/issues/1181 for details.

*Testing*:
CI

*Documentation*:
N/A

Follow up needs to enable tests with all the below fixed.
Failing tests:
```
[  FAILED  ] 11 tests, listed below:
[  FAILED  ] OpenCL/Operator.matMul/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.Transpose3Dims/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.ScatterAssign/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.TestQuantizedRescaleSequence/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.Squeeze/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.ExpandDims/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.Reshape/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.ReshapeInt/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.sliceReshape/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.Flatten/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.QuantizeSimple/0, where GetParam() = 4-byte object <01-00 00-00>


[  FAILED  ] OpenCL/BackendTest.simplePlaceholderValue/0, where GetParam() = 4-byte object <01-00 00-00> (103 ms)
```

### CODE REVIEW

**Comment by opti-mix** [comment]
@rdzhabarov Thanks a lot for looking into this! 

As far as I understand, you managed to make the OpenCL backend and tests compile and link during the CI builds by making use of POCL. This is a pretty big step already! Great progress! This would allow us to catch any source-breaking changes.

The remaining problems seem to be related to the test execution failures. Fixing those would be nice as well, but this is a separate issue, IMHO.

BTW, when I was working on the OpenCL backend I've often used the debug-instrumentation to compare runs on different OpenCL devices and detect when they start to diverge from each other. So, may be we should just try to compare a run of a failing test on a local machine using `-opencl -device 0` (which is a CPU) with a run on the CI machine, which uses POCL to run on a CPU. May be we'll see something interesting.

**Comment by rdzhabarov** [comment]
> I've often used the debug-instrumentation to compare runs on different OpenCL devices

I tried to enable it and saw core dump, need to investigate that.

**Comment by rdzhabarov** [comment]
@opti-mix finally made this work, some tests are skipped and we can work on that in follow up prs.

**Comment by opti-mix** [comment]
@rdzhabarov Very cool! Thanks a lot for finding a way to build it on CI!

**Comment by rdzhabarov** [comment]
Yes, I'll split into two commits here

**Comment by opti-mix** [comment]
@rdzhabarov I reproduced locally and found the reason for the failing tests. There is a bug in POCL! I created an issue: https://github.com/pocl/pocl/issues/677

**Comment by opti-mix** [comment]
@rdzhabarov Apparently, they fixes this bug two weeks ago on their master branch. So, if you'd just build their master instead of the specific version you were using so far, all tests would pass. I checked it locally and they all pass.

**Comment by rdzhabarov** [comment]
nice! let me update that.

**Pull request merged**
