### PR TITLE
Add images argument to resnet example tests

### PR DESCRIPTION
**Pull request by jackm321**
*Description*:
As title.
Also don't create text-translator variable because now we're passing in bin as variable so it's kind of redundant.

*Testing*:
`ninja check_expensive`
CI

*Documentation*:
none

### CODE REVIEW

**Comment by jackm321** [comment]
If anyone who is less of a shell scripting noob than me can tell me a good way to output the results of the command being piped into OutputCheck if OutputCheck fails (or even no matter the result) that would be awesome. I was messing around with `tee` but it didn't seem to do what I wanted here.

**Comment by nickgg** [comment]
Can you just redirect to a file in tmp/ then cat it?

**Comment by jackm321** [comment]
@nickgg yeah I was thinking about doing that with tmpfile, that's probably the way to go

**Comment by jackm321** [comment]
@jfix71 I'm going to land this again, hopefully this fixes the issue from this morning, if not it may be an environment issue on CI or something.

**Pull request merged**
