### PR TITLE
Concat over axis 1 in loadIndexPut to avoid extra transpose

### PR DESCRIPTION
**Pull request by mudeshi1209**
### Summary:

Current code concats over axis 0 and then transposes.
The extra transpose can be avoided by doing concat over
axis 1 directly.

### Test Plan:

The torch_glow index_put_test.py tests this change.

Please see a detailed explanation of how to fill out the fields in the relevant sections in PULL_REQUEST.md.

### CODE REVIEW

**Comment by mudeshi1209** [comment]
@sgeorgiev255  pls review this change.

**Comment by mudeshi1209** [comment]
Hi @jfix71 , please review this PR.

**Comment by zrphercule** [comment]
Hi @mudeshi1209  Is there any specific reason you want to remove this transpose? Since it seems although you can ignore this transpose, you will have create reshape node instead of one.

**Comment by mudeshi1209** [comment]
@zrphercule The new reshapes are equivalent to unsqueeze operation and do not lead to any data movement. The transpose however, requires data movement and cannot be ignored. In the graph I am testing with, this Transpose is not optimized away and consumes cycles at runtime, whereas the reshapes become No-op.

**Comment by mudeshi1209** [comment]
@zrphercule Is there any other clarification you require? If not can you review this patch again?

**Comment by zrphercule** [comment]
> @zrphercule Is there any other clarification you require? If not can you review this patch again?

Are I missed your last reply. This diff looks good, I will import it to FB for test internally tomorrow.

**Review by zrphercule — APPROVED** [review]

**Pull request closed without merging**
