### PR TITLE
[ONNXImporter] Support If operator with constant condition

### PR DESCRIPTION
**Pull request by aturetsk**
Author: Max Kazantsev <maximkaz@cadence.com>

Summary: Limited support for If ONNX operator, when the condition input is a constant. The node is substituted by "then" or "else" sub-graph based on the condition in loader.

Documentation: N/A

Test Plan: Added ONNXImporter unit tests.

### CODE REVIEW

**Comment by aturetsk** [comment]
CI failures do not look related to the changes in this PR:
```
FAILED tests/nodes/quantized_conv2d_test.py::TestQuantizedConv2d::test_quantized_conv2d_packed_channelwise
FAILED tests/nodes/quantized_conv2d_test.py::TestQuantizedConv2d::test_quantized_conv2d_packed_channelwise_parallel_qconv
FAILED tests/nodes/quantized_conv2d_test.py::TestQuantizedConv2d::test_quantized_conv2d_packed_channelwise_serial_qconv
```

**Comment by aturetsk** [comment]
Ping

**Review by jfix71 — APPROVED** [review]
Cool. I am wondering if it is necessary to directly fold in the loader -- don't we already have an opt pass that will get rid of the LHS or RHS subgraphs if the condition input is constant? Why not just load it as is and let the graph opts take over?

**Comment by aturetsk** [comment]
@jfix71, thanks for review!
Unless I'm missing something, there is no IF node in Glow, so we can't optimize it out in a graph-level pass. Could it be that you mixed it up with Select optimization, where we throw away RHS or LHS if its condition input is a uniform constant? https://github.com/pytorch/glow/blob/9944a1e2df4166df8b51758166f9fdc35cf6a1eb/lib/Optimizer/GraphOptimizer/GraphOptimizer.cpp#L3307-L3314

**Comment by jfix71** [comment]
@aturetsk Sorry yes, I was referring to implementing an if via a select. You're just executing both branches of the if, and selecting the one you want based on the condition.

**Pull request closed without merging**
