### PR TITLE
Update LSTM unittests thresholds

### PR DESCRIPTION
**Pull request by omromano**
Summary: Update LSTM unittests thresholds to match HW precision.

### CODE REVIEW

**Review by zrphercule — COMMENTED** [review]
Cool. I wonder which HW the old thresholds does not work?

**Comment by omromano** [comment]
> Cool. I wonder which HW the old thresholds does not work?
@zrphercule I think these tests are using the LSTMUnit nodes which are new and work only on the Interpreter backend.

**Comment by zrphercule** [comment]
> > Cool. I wonder which HW the old thresholds does not work?
> > @zrphercule I think these tests are using the LSTMUnit nodes which are new and work only on the Interpreter backend.

I see, are these test currently breaking in our codebase running on Interpreter? When creating this I thought 1e-5 was big enought, since other tests are using 1e-7 or even less.

**Comment by omromano** [comment]
> > > Cool. I wonder which HW the old thresholds does not work?
> > > @zrphercule I think these tests are using the LSTMUnit nodes which are new and work only on the Interpreter backend.
> 
> I see, are these test currently breaking in our codebase running on Interpreter? When creating this I thought 1e-5 was big enought, since other tests are using 1e-7 or even less.

I don't think it should break current code. I'm testing with NNP-I HW changes.

**Review by zrphercule — APPROVED** [review]

**Comment by zrphercule** [comment]
LGTM, Thanks!

**Comment by zrphercule** [comment]
Sorry I mistakely clicked the "close"...

**Pull request closed without merging**
