### PR TITLE
Fixes a bug in isOverlappingWithAnyBundleBufferOperands() where outpu…

### PR DESCRIPTION
**Pull request by andreas-hommel**
There is a bug in the overlap checking when merging kernels. When checking if a new instruction can be merged, you currently only check if an added output overlaps any of the buffers used by the bundle. This is not enough because and added input buffer could also overlap with an existing output buffer in the bundle.

This fix removes the "op.second == OperandKind::In" "continue," and adds overlap checking for "to be added" inputs against bundle outputs.

This fixes a failure in one of our internal tests. Note that this is loosely related/and addendum to my fix to preserve "noalias" attributes (commit d882a61a88a82b5a99bbda360d97e4765b38a422).

### CODE REVIEW

**Comment by opti-mix** [comment]
@andreas-hommel Overall, it looks reasonable. But'd like to ask you about something. 
1) Do you need to treat InOut in a special way? Or do you consider them to be mutating and thus effectively "Out" operands?

2) Also, what about situations, where you have e.g. sequences of elementwise operations that reuse one of their input operands for outputs to save memory and to avoid copying things around. Would your change prohibit stacking of such sequences?

**Comment by andreas-hommel** [comment]
I just copied the current behavior that treats "InOut" the same as "Out".
So yes, this another change that will prevent/stacking stacking at a point where input/output overlaps another output, but this is necessary for the "noalias" attributes.

FWIW in our internal use-case that broke after the "noalias" fix (from last month) the original code had a long sequence of LLVM generated vectorization legality runtime pointer checks to see if the pointers overlap and that ended up executing the scalar/elementwise loop. With the fix we had two kernels, but they were fully vectorized without any legality checks, so the correct/fixed code is much faster and smaller.

**Comment by andreas-hommel** [comment]
Reviving this discussion. I have been thinking about a better way to handle "noalias" with stacked kernels. The problem is that we have multiple pointers that refer to the same object. My new idea is to merge the pointers that refer to the same object, that we can stack the kernels because all accesses to the same object will go through the same pointer, with that will will have leag "noalias" attributes and there LLVM will be able to figure out the correct data dependencies.

I have implemented this on my end, but I am getting failures in some trivial tests, e.g., this test

```
[ RUN      ] CPU/OperatorStatelessTest.BasicMinNetFloatVsInt8/0
I0319 14:11:14.826267 29297 BackendTestUtils.cpp:283] Comparing Interpreter with precision float against CPU with precision i8 with Bias i32 with FP16 AccumulationSLS 0
I0319 14:11:14.828969 29297 Partitioner.cpp:684] Profiling a model to be partitioned cross different backends. Each sub-network will be optimized and run on cpu backend.
#### Merged 1 into 0
%A = WeightVar float<1 x 4> mutable @0
%arith_res = allocactivation  { Ty: float<1 x 4>} @0
  call void @libjit_stacked_kernel(float* %10, float* %14, float* %18, float* %22)
define internal void @libjit_stacked_kernel(float*, float*, float*, float*) {
entry:
  br label %loop

loop:                                             ; preds = %loop, %entry
  %4 = phi i64 [ 0, %entry ], [ %nextvar, %loop ]
  %5 = call float @libjit_element_min_kernel_f(i64 %4, float* %1, float* %2, float* null)
  %buffer.element.addr = getelementptr float, float* %0, i64 %4
  store float %5, float* %buffer.element.addr
  %6 = call float @libjit_copy_kernel_f(i64 %4, float* %0, float* null, float* null)
  %buffer.element.addr1 = getelementptr float, float* %3, i64 %4
  store float %6, float* %buffer.element.addr1
  %nextvar = add nuw nsw i64 %4, 1
  %loopcond = icmp ult i64 %nextvar, 4
  br i1 %loopcond, label %loop, label %afterloop, !llvm.loop !4

afterloop:                                        ; preds = %loop
  ret void
}

```

will be rewritten to

```
define internal void @libjit_stacked_kernel(float*, float*, float*, float*) {
entry:
  br label %loop

loop:                                             ; preds = %loop, %entry
  %4 = phi i64 [ 0, %entry ], [ %nextvar, %loop ]
  %5 = call float @libjit_element_min_kernel_f(i64 %4, float* %0, float* %2, float* null)
  %buffer.element.addr = getelementptr float, float* %0, i64 %4
  store float %5, float* %buffer.element.addr
  %6 = call float @libjit_copy_kernel_f(i64 %4, float* %0, float* null, float* null)
  %buffer.element.addr1 = getelementptr float, float* %3, i64 %4
  store float %6, float* %buffer.element.addr1
  %nextvar = add nuw nsw i64 %4, 1
  %loopcond = icmp ult i64 %nextvar, 4
  br i1 %loopcond, label %loop, label %afterloop, !llvm.loop !4

afterloop:                                        ; preds = %loop
  ret void
}
```

so the only change is that %1 of the libjit_element_min_kernel_f() call is rewritten to %0 because my compile time check:

```
/// Check if an operand exactly overlaps with another operand.
///
/// \param allocInfo information about allocations
/// \param buf1 a buffer operand
/// \param buf2 the buffer operand to be checked for overlaps with the \p buf1.
static bool isExactBufferOverlap(AllocationsInfo &allocInfo, Value *buf1, Value *buf2) {
  return buf1->getType() == buf2->getType() &&
    buf1->getSizeInBytes() == buf2->getSizeInBytes() &&
    allocInfo.allocatedAddress_[buf1] == allocInfo.allocatedAddress_[buf2];
}
```

Determines that %0 and %1 refer to the same buffer region. So this should be a legal transformation, or is there another optimization happening after the stacking that could somehow change the arguments that are passed to the kernel?

**Comment by opti-mix** [comment]
@andreas-hommel Could you provide a PR to reproduce the issue you describe? It seems like your approach should work in theory, but it is hard to say what goes wrong without a reproducer.

**Comment by andreas-hommel** [comment]
I have push my changes to:

https://github.com/andreas-hommel/glow/tree/kernel-stack-fix

It is work in progress with some debug hacks. GLOW's "ninja check" will fail several tests with this, e.g.:

```
[ RUN      ] CPU/OperatorStatelessTest.BasicMaxNetFloatVsInt8/0
I0319 15:30:50.417804 27188 BackendTestUtils.cpp:283] Comparing Interpreter with precision float against CPU with precision i8 with Bias i32 with FP16 AccumulationSLS 0
I0319 15:30:50.420938 27188 Partitioner.cpp:684] Profiling a model to be partitioned cross different backends. Each sub-network will be optimized and run on cpu backend.
#### Merged 1 into 0
%A = WeightVar float<1 x 4> mutable @0
%arith_res = allocactivation  { Ty: float<1 x 4>} @0
  call void @libjit_stacked_kernel(float* %10, float* %14, float* %18, float* %22)2: %B = WeightVar float<1 x 4> mutable @64
0: %A = WeightVar float<1 x 4> mutable @0
3: %save = WeightVar float<1 x 4> mutable @512
0: %arith_res = allocactivation  { Ty: float<1 x 4>} @0

define internal void @libjit_stacked_kernel(float* noalias, float* noalias, float* noalias, float* noalias) {
entry:
  br label %loop

loop:                                             ; preds = %loop, %entry
  %4 = phi i64 [ 0, %entry ], [ %nextvar, %loop ]
  %5 = call float @libjit_element_max_kernel_f(i64 %4, float* %0, float* %2, float* null)
  %buffer.element.addr = getelementptr float, float* %0, i64 %4
  store float %5, float* %buffer.element.addr
  %6 = call float @libjit_copy_kernel_f(i64 %4, float* %0, float* null, float* null)
  %buffer.element.addr1 = getelementptr float, float* %3, i64 %4
  store float %6, float* %buffer.element.addr1
  %nextvar = add nuw nsw i64 %4, 1
  %loopcond = icmp ult i64 %nextvar, 4
  br i1 %loopcond, label %loop, label %afterloop, !llvm.loop !4

afterloop:                                        ; preds = %loop
  ret void
}
I0319 15:30:50.562302 27188 HostManager.cpp:249] Destroying host manager...
I0319 15:30:50.562973 27188 Partitioner.cpp:482] The model is too small for applying partition.
Model size : 32
Backend Name : Interpreter
Device memory: 2000000000
I0319 15:30:50.564270 27188 Partitioner.cpp:88] The number of partitions is : 1
I0319 15:30:50.564286 27188 PartitionerUtils.cpp:537] 	 Partition 0:
		 Name :	main
		 BackendKind :	Interpreter
		 context count :	1
		 total Memory :	48
			 input size:	32
			 input count :	2
			 output size:	16
			 constant size:	0
I0319 15:30:50.564297 27188 PartitionerUtils.cpp:556] 		 LogicalDeviceIDs :	0
I0319 15:30:50.566164 27188 Partitioner.cpp:482] The model is too small for applying partition.
Model size : 32
Backend Name : CPU
Device memory: 2000000000
I0319 15:30:50.568020 27188 Partitioner.cpp:88] The number of partitions is : 1
I0319 15:30:50.568039 27188 PartitionerUtils.cpp:537] 	 Partition 0:
		 Name :	main
		 BackendKind :	CPU
		 context count :	1
		 total Memory :	12
			 input size:	8
			 input count :	2
			 output size:	4
			 constant size:	0
I0319 15:30:50.568048 27188 PartitionerUtils.cpp:556] 		 LogicalDeviceIDs :	0
I0319 15:30:50.679075 27188 Tensor.h:971] Tensors not equal: 4 out of 4 elements exceeded allowed error threshold 0.035. Maximum error found was 2.7 at index 3: 2.7 vs. 0
I0319 15:30:50.679119 27188 Tensor.h:977] Maximum relative error found was: 1 at index: 0: 1.8 v.s. 0
/home/nxa08079/env_autopar/glow/glow/tests/unittests/BackendTestUtils.cpp:343: Failure
Value of: finalIT.isEqual(finalBT, allowedError, true)
  Actual: false
Expected: true
I0319 15:30:50.679893 27188 HostManager.cpp:249] Destroying host manager...
I0319 15:30:50.681224 27188 HostManager.cpp:249] Destroying host manager...
[  FAILED  ] CPU/OperatorStatelessTest.BasicMaxNetFloatVsInt8/0, where GetParam() = ("CPU") (264 ms)

```

**Comment by andreas-hommel** [comment]
#5539 has been merged so the pull is now obsolete.

**Comment by andreas-hommel** [comment]
@opti-mix 

I tried my local optimization from

https://github.com/andreas-hommel/glow/tree/kernel-stack-fix

to allow more kernel stacking. I think there is a bug in the allocator:

For CPU/BackendCorrectnessTest.dataParallelStackingTest I get:

```
  call void @libjit_stacked_kernel.4(float* %34, float* %38, float* %42)

2: %tv2 = tensorview @in %act1 { Ty: float<2>, Offsets: [1]} @4
0: %output1 = WeightVar float<2> mutable @0
1: %tv1 = tensorview @in %act1 { Ty: float<2>, Offsets: [0]} @0

define internal void @libjit_stacked_kernel.4(float* noalias, float* noalias, float* noalias) {
entry:
  br label %loop

loop:                                             ; preds = %loop, %entry
  %3 = phi i64 [ 0, %entry ], [ %nextvar, %loop ]
  %4 = call float @libjit_element_add_kernel_f(i64 %3, float* %1, float* %0, float* null)
  %buffer.element.addr = getelementptr float, float* %0, i64 %3
  store float %4, float* %buffer.element.addr
  %nextvar = add nuw nsw i64 %3, 1
  %loopcond = icmp ult i64 %nextvar, 2
  br i1 %loopcond, label %loop, label %afterloop, !llvm.loop !4

afterloop:                                        ; preds = %loop
  ret void
}
```

Here the output1 gets allocated to 0 even though it is full overlapping tv1 and partially overlapping tv1.
I think this is too aggressive why my optimization fails. output1 should really have it's own independent space.

**Pull request closed without merging**
