### PR TITLE
[LIBJIT] Remove heap usage from Gemm.

### PR DESCRIPTION
**Pull request by mciprian13**
**Summary**
Remove the Gemm branch where heap and extra stack is used.

**Documentation**
None

**Test Plan**
None

### CODE REVIEW

**Comment by mciprian13** [comment]
@opti-mix Opened this PR as discussed in  #3751.

**Comment by mciprian13** [comment]
Not sure why the Pytorch CI build fails but this PR should be ready.

**Comment by opti-mix** [comment]
@mciprian13 CI says this PR is not mergeable anymore. Could you rebase it on top the current master?

**Comment by mciprian13** [comment]
Did it.

**Pull request closed without merging**
