### PR TITLE
[LLVM][LIBJIT] Refactor LLVM libjit CMake infrastructure. 

### PR DESCRIPTION
**Pull request by mciprian13**
**Summary**

Refactor the LLVM libjit CMake infrastrcture by adding a CMake function utility **glow_add_libjit** which allows building libjit libraries more easily (e.g. building more than one libjit version with different source files, compile options, etc).

Also refactor the current LLVM/CPU libjit by:
- moving the LLVM backend specific libjit code in `LLVMIRCodeGen/libjit`
- keeping the CPU backend specific libjit code in `Backends/CPU/libjit_cpu`

This way there is a cleaner separation between the common LLVMBackend LIBJIT code and the CPU specific LIBJIT code.

**Test Plan**
Current unit tests pass.

### CODE REVIEW

**Comment by opti-mix** [comment]
@mciprian13 Thanks for working on this!

Heads-up: Reviewing and landing it may take a while as it will break internal builds, which are using a different build system called buck used by FB. And porting CMake changes to buck is usually rather time-consuming.

**Comment by opti-mix** [comment]
> And porting CMake changes to buck is usually rather time-consuming.

I mean someone on our side would need to port these CMake changes to buck before we can land.

**Comment by opti-mix** [comment]
In the meantime, a couple of related ideas:

- Have you considered extending the APIs for accessing/using libjit? E.g. the ability to have multiple different libjits for a single backend (e.g. for different processor models/operation modes on the same architecture or something like this) and some APIs to pick one of them when Glow runs depending on e.g. command-line flags or configuration? 

- Another direction: Improving the "composabilty" of libjit. What if there would be multiple BC files and you could dynamically select/specify which subset of them (e.g. core, fp-supporting functions, quantization supporting functions, etc) you need for the current compilation?

WDYT?

**Comment by mciprian13** [comment]
> @mciprian13 Thanks for working on this!
> 
> Heads-up: Reviewing and landing it may take a while as it will break internal builds, which are using a different build system called buck used by FB. And porting CMake changes to buck is usually rather time-consuming.

Ok got it.

**Comment by mciprian13** [comment]
> In the meantime, a couple of related ideas:
> 
> * Have you considered extending the APIs for accessing/using libjit? E.g. the ability to have multiple different libjits for a single backend (e.g. for different processor models/operation modes on the same architecture or something like this) and some APIs to pick one of them when Glow runs depending on e.g. command-line flags or configuration?
> * Another direction: Improving the "composabilty" of libjit. What if there would be multiple BC files and you could dynamically select/specify which subset of them (e.g. core, fp-supporting functions, quantization supporting functions, etc) you need for the current compilation?
> 
> WDYT?

- Currently it shouldn't be too hard for a Backend to build multiple LIBJIT files, allocate multiple BC buffers and have a command line argument to modify the behavior of the `getLibjitBitcode()` function to select the desired LIBJIT. Are you suggesting to have this functionality by default in the LLVMBackend and have all the derived backends inherit it? If yes, I'm not sure that all the LLVM backends want it ... Or maybe we can have a default behavior when only one LIBJIT is required/used. Maybe add a parameter to the `getLibjitBitcode()` function like a string or something?
- For LIBJIT subset selection I guess some extra modifications are required in LLVMIRGen. Sounds interesting but seems too generic (at least for my needs) and I have not considered this case.

**Comment by opti-mix** [comment]
> Currently it shouldn't be too hard for a Backend to build multiple LIBJIT files, allocate multiple BC buffers and have a command line argument to modify the behavior of the getLibjitBitcode() function to select the desired LIBJIT. Are you suggesting to have this functionality by default in the LLVMBackend and have all the derived backends inherit it? If yes, I'm not sure that all the LLVM backends want it ... Or maybe we can have a default behavior when only one LIBJIT is required/used. Maybe add a parameter to the getLibjitBitcode() function like a string or something?

Yes, exactly, I was thinking about something like this. By default, a single default bitcode buffer would be selected. But as the functionality would live in LLVMBackend now, any derived backend can make use of it and add more bitcode buffers if needed. I suspect making Glow's CMake machinery support this will be the more difficult part than adding a parameter to getLibjitBitcode.

**Comment by opti-mix** [comment]
> For LIBJIT subset selection I guess some extra modifications are required in LLVMIRGen. Sounds interesting but seems too generic (at least for my needs) and I have not considered this case.

I think this feature could consist of the following parts:
- The ability to create multiple libjit buffers in the same backend (or by other means?)
- The ability to load multiple libjit buffers into the same LLVMIRCodeGen, i.e. to compose them. So, in a way it is similar to the other timer, except we load multiple BCs into the same LLVMIRCodeGen/LLVMContext.

**Comment by tlepley-cadence** [comment]
Note that in our backend, we 'link' together multiple libjit modules. We do it for supporting user custom ops, since each custom op comes with its own libjit module.

**Comment by mciprian13** [comment]
@opti-mix Any news on this? Can we remove the "stale" label? Thanks!

**Comment by opti-mix** [comment]
@mciprian13 Sorry, was too busy with other stuff. Haven't integrated it with buck yet.

**Comment by opti-mix** [comment]
@mciprian13 Could you please resolve the merge conflicts that GH shows in the meantime?

**Comment by mciprian13** [comment]
@opti-mix I solved the conflicts. I have one totally unrelated question:
- What is the reason behind unique-ing types within the Module? Is it a functional problem if I don't unique a type when I instantiate a Node? Is it a sort of memory-optimization thing?

**Comment by opti-mix** [comment]
@mciprian13 

> What is the reason behind unique-ing types within the Module? Is it a functional problem if I don't unique a type when I instantiate a Node? Is it a sort of memory-optimization thing?

Yeah, IIRC it is some sort of memory optimization. It also follows the LLVM pattern, which also uniques the types in the module. I'm not sure we heavily rely on the uniqueness of types anywhere, but there could be a couple of places, where we compare two types by TypeRef pointers instead of using a proper isEqual method. Should be easy to fix though, if needed.

**Comment by opti-mix** [comment]
@mciprian13 Could you please rebase and resolve conflicts again? libjit.cpp seems to have a conflict.

I was planning to spend some time on the buck support, but found that there is still a merge conflict.

**Comment by mciprian13** [comment]
@opti-mix I solved the conflicts.

**Pull request closed without merging**
