### PR TITLE
Force to verify MatMulInst operands count.

### PR DESCRIPTION
**Pull request by lygstate**
Used to trigger the error.

### CODE REVIEW

**Comment by nadavrot** [comment]
@lygstate Thanks for doing this work.  Can you please use a regular assert()? GLOW_ASSERT is used for runtime checks.  Glow uses assert() in a similar way to how LLVM uses asserts to check for internal errors.

**Comment by lygstate** [comment]
@nadavrot Regular assert for what? do you want me to print something or some other reason?

**Comment by lygstate** [comment]
@nadavrot We already have the test result:
```
../lib/Backends/Interpreter/InterpreterNodes.cpp:1207: failed assertion `I->getNumOperands() == 3 && "MatMulInst should have 3 operands"'

```

**Comment by jfix71** [comment]
@lygstate `GLOW_ASSERT()` is not removed for release builds. We prefer these sorts of checks to be used with regular `assert()` which is.

**Comment by nadavrot** [comment]
@lygstate Ah, sorry. I missed the fact that this is just a test commit. Thanks.

**Comment by opti-mix** [comment]
I have an idea how this could happen. Probably this happened during the execution of some predication tests.

Look at the following code:
```c++
void Instruction::setPredicate(Value *p) {
  // Push a new predicate.
  if (!hasPredicate()) {
    predicateIndex_ = getNumOperands();
    pushOperand({p, OperandKind::In});
  }

  setOperand(predicateIndex_, p);
}
```

It seems like it would add a new operand to any instruction which doesn't have a predicate yet and thus increase the reported number of operands, because  `getNumOperands` currently reports the size of the `ops` vector, including the predicate.

One way to solve it may be to change getNumOperands() to take the existence of a predicate into account and ignore it, i.e. something like this:

```c++
unsigned getNumOperands() const { return ops_.size() - (hasPredicate() ? 1 : 0) ; }
```

Does it make sense?

**Comment by nadavrot** [comment]
When we discussed the predicate design we decided to add it as a formal operand to simplify the scheduler and other optimizations that scan the operand list.

**Comment by lygstate** [comment]
Add extra function getInstNumOperands()?

**Comment by bertmaher** [comment]
Fixed by #1206 -- thanks so much for reporting & reproing this!

**Pull request closed without merging**
