### PR TITLE
[bug fix] Weights serialization in utils/scripts/gen_caffe2_model.py

### PR DESCRIPTION
**Pull request by wayneshawn**
*Description*:
Weights serialization for C2 models was broken and `net` was used instead of `weights`.
This PR fixes this bug.

*Testing*:
Running gen_caffe2_models.py and check `init_net.pb` file.

*Documentation*:
None.

### CODE REVIEW

**Comment by beicy** [comment]
Thanks for fixing this bug! Could you please squash the 2 commits before merging?

**Comment by nadavrot** [comment]
@wayneshawn I agree with @beicy.  Also, can you please provide a meaningful description to the pull request and the commits?

**Comment by nadavrot** [comment]
@wayneshawn Nice!

**Comment by wayneshawn** [comment]
@beicy @nadavrot sorry for late reply ^_^, maybe you could check that models in glow/tests/models/caffe2Models be okay for tests.

**Pull request merged**
