### PR TITLE
improve const folding for 16b

### PR DESCRIPTION
**Pull request by lzao-cadence**
Summary:
Improve constant folding for 16b cases.

### CODE REVIEW

**Review by zrphercule — COMMENTED** [review]
Hi, thanks for your diff!
First of all, could you please sign up the CLA as mentioned above?

**Comment by lzao-cadence** [comment]
Ping

**Comment by lzao-cadence** [comment]
all checks have passed.

**Comment by zrphercule** [comment]
I'll import & review it, thanks!

**Pull request closed without merging**
