### PR TITLE
[GraphOptz] Eliminate size limit for constant deduplication optimization

### PR DESCRIPTION
**Pull request by mciprian13**
**Summary**
- The current size limit (in number of elements) for the constant deduplication optimization is 256.
- Changed the default value to 0 (meaning no size limit).
- The motivation for this is:
  - Removing the size limit does not increase considerably the compile time for most of the models (which do not have duplicated constants) since the function `Tensor::isBitwiseEqual()` exists rapidly after finding the first mismatching sample (for example I tested this by compiling a MobileNetv1 large network, the compile time increased from 6.57 seconds to 6.61 seconds - an average from 10 runs).
  - This optimization is required for the RNN operators (RNN, GRU, LSTM) when instantiated with multiple time steps. Although the original graph (e.g. after importing the ONNX model) will reuse same weights for all the time steps, if a backend desires to specialize (for example) the FullyConnected operator by rearranging the weights (e.g. with a simple Transpose), the constant folding will create individual Constant nodes for each time step (therefore removing the weight reusage). In this case the generic Glow optimization should kick in and deduplicate the constants.

### CODE REVIEW

**Comment by mciprian13** [comment]
@jfix71 Can you review this please? Thanks!

**Review by jfix71 — APPROVED** [review]
Fine by me. Thanks.

**Comment by mciprian13** [comment]
@jfix71 Thanks a lot for landing the other PR's! What seems to be the problem with this one? The expensive tests seem to indicate a graph hash mismatch error which is strange ... Maybe you could trigger again the CI? Thanks!

**Comment by jfix71** [comment]
>The expensive tests seem to indicate a graph hash mismatch error which is strange

@mciprian13 Rerunning it now, not sure if it's legit, we will see!

I had an issue internally on this, I am not sure the exact reason, it may be due to tests timing out internally on debug because it's trying to merge lots of constants it wasn't before, will figure out soon.

**Comment by jfix71** [comment]
@mciprian13 Actually seems like it may be a merge conflict? Would you mind rebasing the branch? Sorry about the headache.

**Comment by mciprian13** [comment]
@jfix71 Merged the latest master. Still the RELEASE_WITH_EXPENSIVE_TESTS is not working for some reason ...

**Comment by jfix71** [comment]
@mciprian13 I think if you rebase on top of https://github.com/pytorch/glow/pull/4923 it will work. We were previously running constant deduplication every time we ran a constant folding subgraph. And there were a lot of such constant folding subgraphs in the expensive tests, along with a lot of constants to check. And it was causing the test to timeout.

**Comment by mciprian13** [comment]
@jfix71 Thanks for investigating it. I will merge on top of your PR once it gets landed.

**Comment by jfix71** [comment]
@mciprian13 I accidentally landed this along with #4923 and broke CI. It looks like it's breaking because of profiling mode here causing profiling and then quantization to produce different graphs when we do the hash check, since the test is not running in bundle mode:

https://github.com/pytorch/glow/blob/febd304f234e371f1c605d2eb0d43c0666c68790/lib/Runtime/HostManager/HostManager.cpp#L333

Perhaps we should remove the line I linked above, and then just call `optimizeFunctionBeforeLowering()` just before the `optimizeFunction()` here:

https://github.com/pytorch/glow/blob/febd304f234e371f1c605d2eb0d43c0666c68790/tools/loader/Loader.cpp#L695

Another option could be to add something to cctx for whether we're profiling for a model that will be run in emit-bundle mode? Downside is we'd need a new flag to enable when you're going to do profiling for emitting a bundle. So think the first option would be preferable. Thoughts?

**Comment by mciprian13** [comment]
@jfix71  I would prefer the first version since I don't want to break current usage of tools by adding a new flag. Hope this modification does not break the AOT for quantized bundles.

**Pull request closed without merging**
