### PR TITLE
[Readme] Remove nonexistent flag from brew install command

### LINKED ISSUE #2389: Homebrew's `--with-toolchain` gives `Error: invalid option`
When running `brew install --with-toolchain llvm@7` as specified [in the README](https://github.com/pytorch/glow#macos), I got `Error: invalid option: --with-toolchain`. It worked after removing the flag and I was able to compile and run tests. This appears to be a bug in the README.

Mac version: 10.14.3
```
$ brew --version
Homebrew 2.0.1
Homebrew/homebrew-core (git revision fc73; last commit 2019-02-14)
```

### PR DESCRIPTION
**Pull request by alannnna**
Fixes #2389

### CODE REVIEW

**Comment by nadavrot** [comment]
@alannnna 
You can now click "Rebase and merge" to land this PR.

**Comment by rdzhabarov** [comment]
Thank you for fixing this @alannnna

**Comment by alannnna** [comment]
Sorry for the delay. Thanks for the quick review @nadavrot and thanks @rdzhabarov for merging!

**Comment by serhaty** [comment]
Is there any update on this? I had the same issue as well and took a while to reach here.

**Pull request merged**
