### PR TITLE
[cleanup] Move ML tests into separate MLTest.cpp.

### PR DESCRIPTION
**Pull request by rdzhabarov**

### CODE REVIEW

**Comment by nadavrot** [comment]
Did you use git-move during the refactoring? Does git-blame work reasonably well on the refactored files?

**Comment by rdzhabarov** [comment]
yup, I did `git mv` for interpreter test which is now MLTest.

**Comment by rdzhabarov** [comment]
Confirmed, `git blame tests/unittests/MLTest.cpp` works well with the history of prev changes.

**Comment by nadavrot** [comment]
Cool!

**Pull request merged**
