### PR TITLE
Wrap upsample between 2 transpose layers when loading ONNX

### PR DESCRIPTION
**Pull request by dspmihai**
Summary:
When loading an ONNX model with upsample, it is also needed to transpose the input and the output of the upsample node to follow Glow's NHWC layout requirements. For some reason this wrapping was deleted at some point and the loading started to fail. This commit adds it back.

### CODE REVIEW

**Review by 842974287 — COMMENTED** [review]
Thanks for fixing this! Wondering if ONNX upsample op also support 3D and 5D. If so we probably want to handle them or modify assertion in line 2269 to only allow `size() == 4`.

**Comment by dspmihai** [comment]
[The ONNX doc](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Upsample) doesn't specify any limits for this, but I don't think this means that we should support any useless dimensions (6D).
But, when [importing from TF](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/nn.py#L1192), only 4D is supported.
And in [pytorch](https://pytorch.org/docs/stable/generated/torch.nn.Upsample.html) I see that we should support 3D-5D. But PyTorchModelLoader only supports 4D and 5D, right? Is there a reason why temporal input is not supported?

**Comment by 842974287** [comment]
Yeah I agree we don't need to support 6D. For PyTorchModelLoader we only add support when encounter a use case. Currently we don't have use case for 3D so we didn't add support for it.

**Comment by dspmihai** [comment]
Is this ok to be merged?

**Comment by dspmihai** [comment]
@jfix71, is this ok to be merged?

**Review by 842974287 — APPROVED** [review]
Sorry for the delay. LGTM! Thanks for working on this!

**Pull request closed without merging**
