### PR TITLE
[IROptimizer] Teach the share buffers opti how to propagate copies

### LINKED ISSUE #1240: shareBuffers fails to merge chain of copies
As found in #1209, our shareBuffers optimization fails to merge chain of copies.
The problem is illustrated with the test case in #1237.

Copy/pasting the analysis made in #1209:
In a nutshell, our buffer optimization only looks at merging one segment at a time. In the case of the lowering of the load node, we have for the first time potentially more than one copy on a chain to a use (e.g., with the lowering of reshape(load)) .
Now to illustrate the problem with chain of copy, let us consider:
1: a = copy b
2: c = copy a
3: = c
We have the following segments:
a = (1, 2); b = (-,1); c (2, 3)

First we merge c and a:
1: a = copy b
2: a = copy a
3: = a
Now the segments look like:
a = (1, 2), (2, 3); b = (-,1)

When considering merging a with b, we only consider updating the segment of a that encloses the segment of b, thus (1,2).
The updated code looks like:
1: b = copy b
2: a = copy b
3: = a
We don't update the old c segment and end up with a copy in 2 now.

Interestingly, if you delete the useless copies as you go, you actually end up with incorrect code, e.g., for the previous example:
1: b = copy b
---2: a = copy b---- deleted
3: = a <--- a never defined

This is because when we update the instruction, we don't preserve the last definition of the outgoing variable and given we don't update the uses not in the segment, they potentially reference an undefined variable.

It looks like it works just by accident but maybe it was intended this way?

Long story short we need to lift the one-segment-at-a-time limitation (maybe by merging the segments?).

### PR DESCRIPTION
**Pull request by qcolombet**
When coalescing two interval through copies, merge then into one big
interval. This is legal because the buffers have the same value for
that interval.
Given our share buffers optimization only considers one interval at
a time, this effectively teaches it how to consider intervals that
have been copy-coalesced.
    
This fixes #1240.

### CODE REVIEW

**Comment by qcolombet** [comment]
Note: The first two commits are respectively covered by #1237 and #1242.

**Comment by opti-mix** [comment]
@qcolombet Very nice! The fix is rather small and elegant! I'm happy it didn't require any major re-factoring.

Questions/requests:
- Have you run all of our run.sh and other big tests after your change to see if it breaks anything? CI won't catch it. We need to do it locally.
- I'm not very happy with the test. As far as I can see, you took it as is from a real example. But it seems to be too long and noisy as it contains a lot of unrelated nodes. Could you try to shorten and simplify it?

**Comment by qcolombet** [comment]
> Have you run all of our run.sh and other big tests after your change to see if it breaks anything? CI won't catch it. We need to do it locally.

I've already done the run.sh and everything was fine. Do you have any other big tests I should try?

> Could you try to shorten and simplify it?

I may be able to get rid of all the cruft but one tensor insert. Renaming the variables in something sensible should help too :).

**Comment by opti-mix** [comment]
> Do you have any other big tests I should try?

Our big standalone tests: ptb, mnist, cifar10, fr2en, etc

**Comment by qcolombet** [comment]
Thanks for the review @opti-mix !

Could you approve the two pre-requisite PR #1237 and #1242? (Which you already review indirectly as the first two commits of this PR).

Also, ran mnist, cifar10, fr2en, ptb, and char-rnn, results looked good. (Would be nice if the PR was doing that... my laptop doesn't like running those :P)

**Comment by opti-mix** [comment]
> Could you approve the two pre-requisite PR #1237 and #1242? (Which you already review indirectly as the first two commits of this PR).

Done.

> Also, ran mnist, cifar10, fr2en, ptb, and char-rnn, results looked good. (Would be nice if the PR was doing that... my laptop doesn't like running those :P)

You can always try to use `-cpu`. Usually it is quite a bit faster. But yes, if CI could do it, it would be much nicer ;-)

**Comment by nadavrot** [comment]
Awesome 
@qcolombet. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
