### PR TITLE
[Interpreter Backend] Adding Int32ITy as a valid element kind for SliceNodeKind IR

### PR DESCRIPTION
**Pull request by sladwa**
Adding Int32ITy as a valid element kind for SliceNodeKind IR for interpreter backend. This change is required to run constantFoldInLoader on SliceNodeKind operator with Int32ITy

OperatorTest has been modified to add a test case. Added test case has been blacklisted on OpenCL backend

Test Plan: Ninja Test has been run

### CODE REVIEW

**Comment by opti-mix** [comment]
@sladwa Thanks for your contribution! Have you signed the Contributor License Agreement already?

**Comment by sladwa** [comment]
@opti-mix I am covered under Qualcomm’s Corporate CLA (CCLA).  Claudio Caldato (project manager for Glow at FB) should also be able to verify.

**Comment by sladwa** [comment]
@opti-mix Kindly let us know when this PR will be merged to master branch

**Comment by sladwa** [comment]
Ping.

**Comment by sladwa** [comment]
Ping

**Pull request closed without merging**
