### PR TITLE
Fixing ResNet50 training example.

### PR DESCRIPTION
**Pull request by putivsky**
Summary:
Fixing dimensions for ResNet labels.
Documentation:

[Optional Fixes #issue]

Test Plan:

Please see a detailed explanation of how to fill out the fields in the relevant sections in PULL_REQUEST.md.

### CODE REVIEW

**Comment by putivsky** [comment]
https://github.com/pytorch/glow/issues/3559

**Comment by SplitInfinity** [comment]
@putivsky 

Can you show the terminal output? CI will not run this binary so I just want to make sure.

**Comment by putivsky** [comment]
./bin/resnet-training --resnet50=./resnet50 --cifar10=./cifar-10-batches-bin/data_batch_1.bin
Loading resnet50 model.
In debug mode:
Preparing for training.
Differentiating graph.
Compiling backend.
Loading the CIFAR-10 database.
Assigning images/labels bytes.
Training - epoch #0 from total 32
.

**Comment by putivsky** [comment]
In Release:
./bin/resnet-training --resnet50=./resnet50 --cifar10=./cifar-10-batches-bin/data_batch_1.bin
Loading resnet50 model.
Preparing for training.
Differentiating graph.
Compiling backend.
Loading the CIFAR-10 database.
Assigning images/labels bytes.
Training - epoch #0 from total 32
...

**Comment by pfierek** [comment]
Issue: #3497

**Comment by pfierek** [comment]
Still broken on CPU backend, this time with different Assertion:

    ./bin/resnet-training -backend=CPU
    Loading resnet50 model.
    Preparing for training.
    Differentiating graph.
    Compiling backend.
    Loading the CIFAR-10 database.
    Assigning images/labels bytes.
    Training - epoch #0 from total 32
    .resnet-training: /home/pfierek/repositories/pytorch/glow/include/glow/Base/Tensor.h:1297: const 
    Handle<ElemTy> glow::Tensor::getHandle() const & [ElemTy = float]: Assertion 
    `type_.isType<ElemTy>() && "Getting a handle to the wrong type."' failed.

**Comment by putivsky** [comment]
pfierek, example doesn't intent to produce any accuracy, cause it "simulate" training examples for ResNet from MNIST dataset. Thanks for reporting CPU build problem - working on it.

**Comment by pfierek** [comment]
@putivsky ok, thanks for clarification.

**Pull request closed without merging**
