### PR TITLE
[ONNX] Add support for auto_pad=NOTSET

### PR DESCRIPTION
**Pull request by mciprian13**
**Summary**
- Add support for auto_pad=NOTSET in OnnxModelLoader.
- What this means is that when auto_pad=NOTSET the explicit `pads` are used (if not given then default 0 is used).

**Fixes**
 #5614

**Test Plan**
Current unit tests pass.
Added extra unit test in OnnxImporter.

### CODE REVIEW

**Comment by mciprian13** [comment]
@khabinov Can you review this small PR? The failing builds are from upstream and have nothing to do with this PR. Thanks!

**Comment by khabinov** [comment]
LGTM, will check internal CI as well.

**Comment by mciprian13** [comment]
@khabinov Any problems with this PR? Can we have this merged?

**Comment by mciprian13** [comment]
@khabinov I merged latest master to have all the unit tests working. Can you have another look? Thanks!

**Pull request closed without merging**
