### PR TITLE
[Imagenet] Add shufflenet.

### PR DESCRIPTION
**Pull request by artemrakhov**
For ONNX model, I'm only adding one run, because compilation time is quite slow, because Group Convolution is being unrolled to multiple nodes.

### CODE REVIEW

**Comment by artemrakhov** [comment]
@jfix71: a bit less than 3 minutes.

**Comment by nadavrot** [comment]
@artemrakhov Are we still unrolling grouped convolutions? I thought that Man landed the changes that enable grouped convolutions.

**Comment by beicy** [comment]
@nadavrot lowerGroupConvolutionNode is still enabled. Group arg is not supported in OpenCL yet.

**Comment by artemrakhov** [comment]
@beicy: I think you can now return false in `shouldLower` for group conv for Interpreter and CPU backend. OpenCL backend may continue to return true.

Also, we need to support group in Convolution gradients, but this is slightly orthogonal, because all networks in run.sh just do inference.

**Comment by nadavrot** [comment]
@artemrakhov @beicy How are we running any tests if lowering is enabled by default?

**Pull request merged**
