### PR TITLE
[examples] add an option to emit Glow IR

### PR DESCRIPTION
**Pull request by jeehoonkang**

### CODE REVIEW

**Comment by nadavrot** [comment]
Hi @jeehoonkang!

Thanks for working on this.  It looks like a good direction. I have a question about the french-to-english  test. Why do we need to save the IR into a file and not to std::out like the other tests?

**Comment by jeehoonkang** [comment]
@nadavrot Thanks for reviewing!

I add an option to save IR as a file not for a particularly good reason, but fr-to-en already has an option to save DAG as a file and I think probably users want to save IR as a file as well.  But I don't have any preference on it.  Please let me know which way do you want me to revise this PR!

**Comment by nadavrot** [comment]
@jeehoonkang We print the DAG to a file because we need to render it with graphviz. We usually print the instruction list textually to stdout because we need to inspect it with our eyes. Dumping the IR to stdout would make it consistent with other parts of the compiler (such as -dump-llvm-asm).

**Comment by rdzhabarov** [comment]
@jeehoonkang what's the status of this PR?

**Comment by rdzhabarov** [comment]
@jeehoonkang are you planning to work on this PR. I think printing to stdout should be sufficient.
Let me now I can take over.

**Comment by bertmaher** [comment]
I've inadvertently done more-or-less this as part of #1241.  When that is merged every program can be run with -dump-ir or -dump-ir-dag=file.dot.

**Comment by jeehoonkang** [comment]
Sorry for inactivity; was busy working on day job.  I'll restart working on glow soon.  Thanks for guidance!

**Pull request closed without merging**
