### PR TITLE
[Image] Add support for PPM images.

### PR DESCRIPTION
**Pull request by aturetsk**
Summary:
Add support for PPM images as input for models.

Documentation:
N/A

Test Plan:
Added an ImageTest unit test.

### CODE REVIEW

**Comment by aturetsk** [comment]
@yinghai, @zrphercule, attempt #2.
I've moved cat.ppm from "imagenet" into a separate directory, so it should not interfere with CI scripts.

**Review by zrphercule — APPROVED** [review]
LGTM, thanks!

**Comment by zrphercule** [comment]
@aturetsk Unfortunately this breaks Glow's CI once again: https://app.circleci.com/pipelines/github/pytorch/glow/13053/workflows/7b93ef9f-150a-410c-a7ac-3a12954934d0/jobs/95511
Same bug.

We will revert this pr again and wait for your fix...

**Comment by aturetsk** [comment]
Hi @zrphercule,
I don't think the problem is in my PR. Something wrong seems to happen after the changes were imported to Phabricator.
cat_285.ppm is empty in the commit which has been merged:
https://github.com/pytorch/glow/commit/fceb6a1b63cf6f10291cbb15e2420cae58cb8306#diff-05eb6bbff5ad4fbd284f10b33eb61a074cb0f2dbb0ec076427f09c61764d1cd6
However it's not empty in my PR:
https://github.com/pytorch/glow/pull/5559/files#diff-05eb6bbff5ad4fbd284f10b33eb61a074cb0f2dbb0ec076427f09c61764d1cd6

**Comment by zrphercule** [comment]
> Hi @zrphercule,
> I don't think the problem is in my PR. Something wrong seems to happen after the changes were imported to Phabricator.
> cat_285.ppm is empty in the commit which has been merged:
> [fceb6a1#diff-05eb6bbff5ad4fbd284f10b33eb61a074cb0f2dbb0ec076427f09c61764d1cd6](https://github.com/pytorch/glow/commit/fceb6a1b63cf6f10291cbb15e2420cae58cb8306#diff-05eb6bbff5ad4fbd284f10b33eb61a074cb0f2dbb0ec076427f09c61764d1cd6)
> However it's not empty in my PR:
> https://github.com/pytorch/glow/pull/5559/files#diff-05eb6bbff5ad4fbd284f10b33eb61a074cb0f2dbb0ec076427f09c61764d1cd6

Agree, this is very weird. I will land the revert, and could you please submit this diff once again? I would like to check why it is not imported to phabricator. Thanks!

**Pull request closed without merging**
