### PR TITLE
[CPU] Add dedicated Relu and Clip implementations.

### PR DESCRIPTION
**Pull request by mciprian13**
**Summary**
- Disabled the lowering of Relu and Clip in the CPU Backend. Since these two operators are very common they deserve dedicated implementations. Not lowering them makes the searching of patterns more simple (e.g. fuse Conv with Relu/Clip) regardless of the compile stage (pre/post lowering).
- The float Clip kernel is 2.5x faster than the previous which required two operations (CPUMaxSplat + Min).
- Added new quantized Clip unit test.

**Test Plan**
Existing unit tests pass.
Enhanced the `Relu_Int8` unit test and added a new `Clip_Int8` unit test.

### CODE REVIEW

**Comment by mciprian13** [comment]
@jfix71 Could you take a look on this relatively small PR. Thanks!

**Comment by mciprian13** [comment]
@jfix71 The numbers for the dedicated Relu implementation are close (almost identical) to the CPUMaxSplat. The only exception is when the Relu is preceded by as a backend specific node when the CPUMaxSplat is created together with a Rescale node which is pulled from the Relu. In this case the separated Rescale node which is not optimized away has some overhead associated to it but I don't have concrete numbers here.

**Comment by jfix71** [comment]
Got it -- I'm wondering about whether it's really necessarily. It seems like we should be able to treat CPUMaxSplat and Relu the same? In which case we should fix CPUMaxSplat to not need the extra rescale and not add Relu since they should have essentially the same perf.

**Comment by mciprian13** [comment]
@jfix71 I am not sure I have time now to update the CPUMaxSplat implementation to not need a Rescale. But I think it is good to have the dedicated Relu implementation for other LLVM based backends to use it (like our private Backend). Do you think we could have this landed as is? Thanks!

**Comment by mciprian13** [comment]
Opened an issue here #4656 as you suggested. Thanks!

**Pull request closed without merging**
